/* Read-only reviewed feed; learning state stays on this browser. No business API writes. */
(function () {
  'use strict';
  const categories = ['今日研习','热烫原理','烫发设计','排杠技法','中发方案库','顾客沟通','科研与验证','我的收藏 / 学习记录'];
  const subjects = {'热烫原理':'TGA / CA、pH、软化、温度与含水率：用来源和适用条件理解变化。','烫发设计':'脸型、头型、层次、卷度位置与人物风格：从观察推导设计。','排杠技法':'分区、角度、杠径、方向与张力：让技法服务设计。','中发方案库':'中发与中长发的真实设计；仅收录已获公开授权的案例。','顾客沟通':'从需求、处理历史到预期管理，让判断有据可循。','科研与验证':'区分研究证据、门店观察与待验证假设。'};
  const root = document.getElementById('perm-academy-root');
  if (!root) return;
  const KEY = 'perm_academy_learning_v1';
  let state = { favorites: [], completed: [] }, persistent = true;
  try { const saved = JSON.parse(localStorage.getItem(KEY)); if(saved) for(const k of ['favorites','completed']) state[k] = Array.isArray(saved[k]) ? saved[k].filter(x=>typeof x==='string') : []; } catch (_) { persistent = false; }
  let items = [], category = categories[0], query = '', selected = null, error = '', loading = true;
  const esc = v => String(v || '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const dateKey = () => { const p = new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()); return ['year','month','day'].map(k=>p.find(x=>x.type===k).value).join('-'); };
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){persistent=false;}}
  function toggle(kind,id){state[kind]=state[kind].includes(id)?state[kind].filter(x=>x!==id):state[kind].concat(id);save();render();}
  function render(){
    if(selected){
      const x = items.find(x=>x.id===selected); if(!x){selected=null;return render();}
      root.innerHTML = '<article class="academy-detail"><div class="academy-actions"><button data-action="back">← 返回研习</button></div><div class="academy-meta">'+esc(x.category)+' · '+esc(x.evidence.level)+'证据 · '+esc(x.batchDate)+'</div><h3>'+esc(x.title)+'</h3><div class="academy-actions"><button data-action="favorite" aria-pressed="'+state.favorites.includes(x.id)+'">'+(state.favorites.includes(x.id)?'已收藏':'收藏')+'</button><button data-action="complete" aria-pressed="'+state.completed.includes(x.id)+'">'+(state.completed.includes(x.id)?'已学完 ✓':'标记学完')+'</button></div>'+[['核心知识',x.coreKnowledge],['证据依据与适用边界',x.evidence.basis],['门店应用',x.shopApplication],['待验证问题',x.openQuestions],['标签',x.tags.join(' · ')]].map(([h,v])=>'<h4>'+h+'</h4><p>'+esc(v)+'</p>').join('')+'<h4>来源</h4><p><a href="'+esc(x.source.url)+'" target="_blank" rel="noopener noreferrer">'+esc(x.source.author)+'</a><br>原文发布日期：'+esc(x.source.publishedAt || '未注明')+'<br>审核通过 · '+esc(x.reviewedAt)+'</p><p class="academy-note">'+(x.isExample?'教学示例，不是真实顾客案例，也不是已验证科学结论。':'学习内容不替代产品说明、发束测试与现场判断。')+'</p></article>';
    }else{
      const filtered = items.filter(x=>(category===categories[0]?x.batchDate===dateKey():category===categories[7]?(state.favorites.includes(x.id)||state.completed.includes(x.id)):x.category===category) && (!query||[x.title,x.coreKnowledge,...x.tags].join(' ').toLowerCase().includes(query.toLowerCase())));
      root.innerHTML = '<div class="academy-hero"><div class="academy-meta">'+esc(today())+' · 每天建立一点判断力</div><h3>先理解，再动手。</h3><p>从原理到人物设计，把知识变成可复核的门店判断。</p></div><input class="academy-search" type="search" aria-label="检索研习内容" placeholder="检索知识、技法、人物风格" value="'+esc(query)+'"><nav class="academy-categories" aria-label="研习栏目">'+categories.map((c,i)=>'<button data-category="'+i+'" aria-pressed="'+(c===category)+'">'+esc(c)+'</button>').join('')+'</nav><div class="academy-heading"><strong>'+esc(category)+'</strong><span>'+filtered.length+' 条 · 已学 '+state.completed.filter(id=>items.some(x=>x.id===id)).length+'</span></div>'+(loading?'<div class="academy-empty"><h4>正在读取研习内容</h4><p>请稍候。</p></div>':error?'<div class="academy-empty"><h4>暂时无法读取内容</h4><p>请检查网络后重试。收藏和学习记录仍保留。</p><button class="academy-retry" data-action="retry">重新读取</button></div>':filtered.length?filtered.map(x=>'<button class="academy-row" data-id="'+esc(x.id)+'"><span class="academy-meta">'+esc(x.category)+' · '+esc(x.evidence.level)+'证据'+(state.completed.includes(x.id)?' · 已学完':'')+'</span><strong>'+esc(x.title)+'</strong><p>'+esc(x.coreKnowledge.slice(0,100))+'</p></button>').join(''):'<div class="academy-empty"><h4>'+ (query?'没有匹配的内容':category===categories[7]?'你的学习轨迹，从这里开始':'正在积累，质量优先')+'</h4><p>'+ (category===categories[0]?'每日目标 5–8 条；今天还没有审核通过的内容。数量不足时留空，不以示例或未经核实资料凑数。':category===categories[7]?'打开内容即可收藏或标记学完。':(subjects[category]+' 该栏目暂没有审核通过的资料。'))+'</p></div>')+'<p class="academy-note">收藏与学习记录仅保存在当前浏览器，清理网站数据后会丢失；未接跨设备同步。'+(!persistent?'当前浏览器无法保存，记录仅本次页面有效。':'')+'<br>每日自动入库尚未接通；当前仅展示版本化审核内容。</p>';
    }
  }
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.category!==undefined){category=categories[Number(b.dataset.category)];selected=null;render();}else if(b.dataset.id){selected=b.dataset.id;render();}else if(b.dataset.action==='back'){selected=null;render();}else if(b.dataset.action==='favorite')toggle('favorites',selected);else if(b.dataset.action==='complete')toggle('completed',selected);else if(b.dataset.action==='retry')load();});
  root.addEventListener('input',e=>{if(!e.target.matches('.academy-search'))return;const at=e.target.selectionStart;query=e.target.value;render();const input=root.querySelector('.academy-search');input.focus();try{input.setSelectionRange(at,at);}catch(_){}});
  async function load(){loading=true;error='';render();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('docs/perm/academy-feed.v1.json',{cache:'no-cache',signal:controller.signal});if(!r.ok)throw Error('feed');const feed=await r.json();if(feed.schemaVersion!==1||!Array.isArray(feed.items))throw Error('schema');items=feed.items.filter(x=>x&&x.reviewStatus==='approved'&&typeof x.id==='string'&&categories.slice(1,7).includes(x.category)&&typeof x.title==='string'&&typeof x.coreKnowledge==='string'&&x.evidence&&['强','中','弱'].includes(x.evidence.level)&&typeof x.evidence.basis==='string'&&Array.isArray(x.tags)&&x.source&&/^https:\/\//.test(x.source.url)&&/^\d{4}-\d{2}-\d{2}$/.test(x.batchDate)&&(!x.isRealCase||x.authorization==='granted'));}catch(_){error='load';}finally{clearTimeout(timer);loading=false;render();}}
  load();
})();
