(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SalonCustomerDomain=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  function emptyState(){return{customers:[],relations:[],accounts:[],audit:[],nextIds:{customer:1,account:1,audit:1}}}
  function normalizePhone(value){const digits=String(value||'').replace(/\D/g,'');if(!digits)return'';if(digits.length===11)return digits;if(digits.length>11)return digits.slice(-11);return digits}
  function required(value,label){const text=String(value||'').trim();if(!text)throw new Error('请填写'+label);return text}
  function now(){return new Date().toISOString()}
  function audit(state,entityType,entityId,action,before,after,reason){state.audit.push({id:state.nextIds.audit++,entityType,entityId:String(entityId),action,before:before||null,after:after||null,reason:String(reason||''),occurredAt:now()})}
  function createCustomer(state,input){const name=required(input.name,'顾客姓名'),phone=normalizePhone(input.phone);if(phone&&phone.length!==11)throw new Error('手机号需为11位');if(phone&&state.customers.some(c=>c.phone===phone&&c.status!=='anonymized'))throw new Error('该手机号已经建档');const customer={id:state.nextIds.customer++,name,phone,birthday:input.birthday||'',status:'active',createdAt:now(),updatedAt:now()};state.customers.push(customer);state.relations.push({customerId:customer.id,store:required(input.store||'自由手艺人','门店'),owner:String(input.owner||'').trim(),source:input.source||'walkin',tags:String(input.tags||'').split(/[,，]/).map(s=>s.trim()).filter(Boolean)});audit(state,'customer',customer.id,'create',null,customer,'顾客建档');return customer}
  function setCustomerFrozen(state,id,frozen,reason){const customer=state.customers.find(c=>c.id===Number(id));if(!customer)throw new Error('顾客不存在');const before=Object.assign({},customer);customer.status=frozen?'frozen':'active';customer.updatedAt=now();audit(state,'customer',id,frozen?'freeze':'restore',before,Object.assign({},customer),required(reason,'操作原因'));return customer}
  function openAccount(state,input){const customer=state.customers.find(c=>c.id===Number(input.customerId));if(!customer)throw new Error('顾客不存在');if(customer.status!=='active')throw new Error('冻结顾客不能开立会员账户');const type=String(input.type||'');if(!['stored_value','times_card','package'].includes(type))throw new Error('会员账户类型无效');const amount=Number(input.amount||0),units=Number(input.units||0);if(type==='stored_value'&&amount<0)throw new Error('储值金额不能为负数');if(type!=='stored_value'&&units<=0)throw new Error('请填写有效次数');const account={id:state.nextIds.account++,customerId:customer.id,type,accountNo:'T-'+String(state.nextIds.account-1).padStart(6,'0'),name:required(input.name,'卡项名称'),cashBalance:type==='stored_value'?amount:0,bonusBalance:0,remainingUnits:type==='stored_value'?null:units,expiresOn:input.expiresOn||'',status:'active',createdAt:now()};state.accounts.push(account);audit(state,'member_account',account.id,'open',null,account,'测试环境开立');return account}
  function searchCustomers(state,query,status){const q=String(query||'').trim().toLowerCase();return state.customers.filter(c=>(!status||status==='all'||c.status===status)&&(!q||c.name.toLowerCase().includes(q)||c.phone.includes(normalizePhone(q)))).map(c=>({customer:c,relation:state.relations.find(r=>r.customerId===c.id)||null,accounts:state.accounts.filter(a=>a.customerId===c.id)}))}
  function serialize(state){return JSON.stringify(state)}
  function deserialize(value){if(!value)return emptyState();try{const parsed=JSON.parse(value);if(!parsed||!Array.isArray(parsed.customers))return emptyState();return Object.assign(emptyState(),parsed)}catch(_){return emptyState()}}
  return{emptyState,normalizePhone,createCustomer,setCustomerFrozen,openAccount,searchCustomers,serialize,deserialize};
});
