(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SalonEngagementDomain=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function emptyState(){return{works:[],reviews:[],tips:[],campaigns:[],customerBookings:[],audit:[],next:{work:1,review:1,tip:1,campaign:1,booking:1,audit:1}}}
 function req(v,n){v=String(v||'').trim();if(!v)throw Error('请填写'+n);return v}
 function log(s,t,id,a,d){s.audit.push({id:s.next.audit++,type:t,entityId:id,action:a,detail:d,at:new Date().toISOString()})}
 function addWork(s,i){const consent=!!i.customerConsent,evidence=String(i.consentEvidenceRef||'').trim();if(consent&&!evidence)throw Error('请填写顾客授权凭证引用');const r={id:s.next.work++,title:req(i.title,'作品标题'),staffId:Number(i.staffId)||null,customerId:Number(i.customerId)||null,orderId:Number(i.orderId)||null,imageRef:req(i.imageRef,'作品图片引用'),customerConsent:consent,consentEvidenceRef:evidence,status:'draft'};s.works.push(r);log(s,'work',r.id,'create',r);return r}
 function submitWork(s,id){const r=s.works.find(x=>x.id===Number(id));if(!r||r.status!=='draft')throw Error('作品当前不能提交审核');if(r.customerId&&!r.customerConsent)throw Error('未取得顾客授权不能提交公开审核');r.status='pending_review';r.submittedAt=new Date().toISOString();log(s,'work',r.id,'submit',{status:r.status});return r}
 function reviewWork(s,id,status,reason){const r=s.works.find(x=>x.id===Number(id));if(!r||r.status!=='pending_review'||!['published','rejected'].includes(status))throw Error('作品审核状态无效');if(status==='published'&&r.customerId&&!r.customerConsent)throw Error('未取得顾客授权不能发布');r.status=status;r.reviewReason=req(reason,'审核说明');r.reviewedAt=new Date().toISOString();log(s,'work',r.id,'review',{status,reason:r.reviewReason});return r}
 function addReview(s,i){const rating=Number(i.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw Error('评分需为1至5分');const r={id:s.next.review++,orderNo:req(i.orderNo,'订单号'),customerId:Number(i.customerId)||null,staffId:Number(i.staffId)||null,rating,comment:String(i.comment||'').trim(),createdAt:new Date().toISOString()};s.reviews.push(r);const amount=Math.round(Number(i.tip||0)*100)/100;if(amount<0||!Number.isFinite(amount))throw Error('打赏意向金额无效');if(amount>0)s.tips.push({id:s.next.tip++,reviewId:r.id,staffId:r.staffId,amount,status:'pending',createdAt:r.createdAt});log(s,'review',r.id,'create',{rating,tipIntent:amount});return r}
 function addCampaign(s,i){const start=req(i.startsOn,'开始日期'),end=req(i.endsOn,'结束日期');if(end<start)throw Error('活动结束日期不能早于开始日期');const r={id:s.next.campaign++,name:req(i.name,'活动名称'),channel:req(i.channel,'渠道'),audience:req(i.audience,'目标顾客'),startsOn:start,endsOn:end,status:'draft'};s.campaigns.push(r);log(s,'campaign',r.id,'create',r);return r}
 function requestBooking(s,i){const r={id:s.next.booking++,customerName:req(i.customerName,'顾客姓名'),phone:req(i.phone,'手机号'),service:req(i.service,'预约项目'),desiredAt:req(i.desiredAt,'期望时间'),staffName:String(i.staffName||'').trim(),status:'submitted'};s.customerBookings.push(r);log(s,'customer_booking',r.id,'create',r);return r}
 function serialize(s){return JSON.stringify(s)}
 function deserialize(v){try{v=JSON.parse(v);return v&&Array.isArray(v.works)?Object.assign(emptyState(),v):emptyState()}catch(_){return emptyState()}}
 return{emptyState,addWork,submitWork,reviewWork,addReview,addCampaign,requestBooking,serialize,deserialize}
});
