(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SalonOrderDomain=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  function emptyState(){return{orders:[],payments:[],accountLedger:[],audit:[],nextIds:{order:1,line:1,payment:1,ledger:1,audit:1}}}
  function required(value,label){const result=String(value||'').trim();if(!result)throw new Error('请填写'+label);return result}
  function money(value,label){const result=Math.round(Number(value)*100)/100;if(!Number.isFinite(result)||result<0)throw new Error(label+'无效');return result}
  function now(){return new Date().toISOString()}
  function audit(state,type,id,action,detail){state.audit.push({id:state.nextIds.audit++,type,entityId:Number(id),action,detail:detail||{},occurredAt:now()})}
  function findOrder(state,id){const order=state.orders.find(row=>row.id===Number(id));if(!order)throw new Error('订单不存在');return order}
  function assertDraft(order){if(order.status!=='draft')throw new Error('只有草稿订单可以修改')}
  function recalculate(order){order.subtotal=Math.round(order.lines.reduce((sum,line)=>sum+line.unitPrice*line.quantity,0)*100)/100;order.total=Math.max(0,Math.round((order.subtotal-order.discount)*100)/100);return order}
  function createOrder(state,input){const order={id:state.nextIds.order++,orderNo:'OFF-'+String(state.nextIds.order-1).padStart(6,'0'),customerId:input.customerId?Number(input.customerId):null,customerName:String(input.customerName||'散客').trim()||'散客',store:required(input.store||'自由手艺人','门店'),status:'draft',lines:[],subtotal:0,discount:0,total:0,paid:0,createdAt:now(),paidAt:null};state.orders.push(order);audit(state,'order',order.id,'create',{orderNo:order.orderNo,customerId:order.customerId});return order}
  function addLine(state,orderId,input){const order=findOrder(state,orderId);assertDraft(order);const quantity=Number(input.quantity);if(!Number.isInteger(quantity)||quantity<=0||quantity>999)throw new Error('数量需为1至999的整数');const line={id:state.nextIds.line++,type:['service','product'].includes(input.type)?input.type:'service',name:required(input.name,'项目或商品名称'),staff:String(input.staff||'').trim(),unitPrice:money(input.unitPrice,'单价'),quantity};order.lines.push(line);recalculate(order);audit(state,'order_line',line.id,'create',{orderId:order.id,line});return line}
  function removeLine(state,orderId,lineId){const order=findOrder(state,orderId);assertDraft(order);const index=order.lines.findIndex(line=>line.id===Number(lineId));if(index<0)throw new Error('订单明细不存在');const removed=order.lines.splice(index,1)[0];recalculate(order);audit(state,'order_line',removed.id,'remove',{orderId:order.id});return removed}
  function setDiscount(state,orderId,value){const order=findOrder(state,orderId);assertDraft(order);const discount=money(value||0,'优惠金额');if(discount>order.subtotal)throw new Error('优惠金额不能超过订单原价');order.discount=discount;recalculate(order);audit(state,'order',order.id,'discount',{discount});return order}
  function checkout(state,customerState,orderId,paymentInputs){const order=findOrder(state,orderId);assertDraft(order);if(!order.lines.length)throw new Error('请先添加消费项目');const inputs=(paymentInputs||[]).map(row=>({method:String(row.method||''),amount:money(row.amount,'支付金额'),accountId:row.accountId?Number(row.accountId):null})).filter(row=>row.amount>0);if(!inputs.length)throw new Error('请添加支付方式');const paid=Math.round(inputs.reduce((sum,row)=>sum+row.amount,0)*100)/100;if(Math.abs(paid-order.total)>0.009)throw new Error('支付合计必须等于应收金额');const validMethods=['cash','wechat','alipay','member_value'];inputs.forEach(row=>{if(!validMethods.includes(row.method))throw new Error('支付方式无效');if(row.method==='member_value'){const account=customerState.accounts.find(a=>a.id===row.accountId&&a.type==='stored_value');if(!account||account.customerId!==order.customerId)throw new Error('请选择本单顾客的有效储值卡');const customer=customerState.customers.find(c=>c.id===order.customerId);if(!customer||customer.status!=='active'||account.status!=='active')throw new Error('顾客或储值卡当前不可扣款');if(account.cashBalance<row.amount)throw new Error('储值余额不足')}});const paidAt=now();inputs.forEach(row=>{const payment={id:state.nextIds.payment++,orderId:order.id,method:row.method,amount:row.amount,accountId:row.accountId,paidAt};state.payments.push(payment);if(row.method==='member_value'){const account=customerState.accounts.find(a=>a.id===row.accountId);const before=account.cashBalance;account.cashBalance=Math.round((before-row.amount)*100)/100;state.accountLedger.push({id:state.nextIds.ledger++,accountId:account.id,orderId:order.id,type:'consume',amount:-row.amount,balanceBefore:before,balanceAfter:account.cashBalance,occurredAt:paidAt})}});order.status='paid';order.paid=paid;order.paidAt=paidAt;audit(state,'order',order.id,'checkout',{total:order.total,payments:inputs.map(row=>({method:row.method,amount:row.amount,accountId:row.accountId}))});return order}
  function receipt(state,orderId){const order=findOrder(state,orderId);return{order,payments:state.payments.filter(row=>row.orderId===order.id),ledger:state.accountLedger.filter(row=>row.orderId===order.id)}}
  function serialize(state){return JSON.stringify(state)}
  function deserialize(value){try{const parsed=JSON.parse(value);return parsed&&Array.isArray(parsed.orders)?Object.assign(emptyState(),parsed):emptyState()}catch(_){return emptyState()}}
  return{emptyState,createOrder,addLine,removeLine,setDiscount,checkout,receipt,serialize,deserialize,recalculate};
});
