(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SalonSchedulingDomain=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  function emptyState(){return{staff:[],leaves:[],appointments:[],queue:[],audit:[],nextIds:{staff:1,leave:1,appointment:1,queue:1,audit:1}}}
  function text(value,label){const result=String(value||'').trim();if(!result)throw new Error('请填写'+label);return result}
  function iso(value,label){const date=new Date(value);if(!value||Number.isNaN(date.getTime()))throw new Error(label+'无效');return date.toISOString()}
  function audit(state,type,id,action,detail){state.audit.push({id:state.nextIds.audit++,type,entityId:Number(id),action,detail:detail||{},occurredAt:new Date().toISOString()})}
  function addStaff(state,input){const name=text(input.name,'员工姓名');if(state.staff.some(s=>s.name===name&&s.status==='active'))throw new Error('该员工已经存在');const row={id:state.nextIds.staff++,name,station:String(input.station||'').trim(),status:'active'};state.staff.push(row);audit(state,'staff',row.id,'create',row);return row}
  function addLeave(state,input){const staff=state.staff.find(s=>s.id===Number(input.staffId)&&s.status==='active');if(!staff)throw new Error('请选择有效员工');const startsAt=iso(input.startsAt,'休假开始时间'),endsAt=iso(input.endsAt,'休假结束时间');if(endsAt<=startsAt)throw new Error('休假结束时间必须晚于开始时间');const row={id:state.nextIds.leave++,staffId:staff.id,startsAt,endsAt,reason:text(input.reason,'休假原因')};state.leaves.push(row);audit(state,'leave',row.id,'create',row);return row}
  function overlaps(aStart,aEnd,bStart,bEnd){return aStart<bEnd&&bStart<aEnd}
  function createAppointment(state,input){const staff=state.staff.find(s=>s.id===Number(input.staffId)&&s.status==='active');if(!staff)throw new Error('请选择有效员工');const startsAt=iso(input.startsAt,'预约时间'),duration=Number(input.duration||0);if(!Number.isInteger(duration)||duration<15||duration>720)throw new Error('预约时长需为15至720分钟');const endsAt=new Date(new Date(startsAt).getTime()+duration*60000).toISOString();if(state.leaves.some(l=>l.staffId===staff.id&&overlaps(startsAt,endsAt,l.startsAt,l.endsAt)))throw new Error('该员工此时段休假或不可预约');if(state.appointments.some(a=>a.staffId===staff.id&&!['cancelled','no_show'].includes(a.status)&&overlaps(startsAt,endsAt,a.startsAt,a.endsAt)))throw new Error('该员工此时段已有预约');const row={id:state.nextIds.appointment++,staffId:staff.id,customerName:text(input.customerName,'顾客姓名'),customerPhone:String(input.customerPhone||'').replace(/\D/g,''),service:text(input.service,'预约项目'),startsAt,endsAt,duration,status:'confirmed',specified:!!input.specified,notes:String(input.notes||'').trim(),source:input.source||'staff'};state.appointments.push(row);audit(state,'appointment',row.id,'create',row);return row}
  function setAppointmentStatus(state,id,status){const row=state.appointments.find(a=>a.id===Number(id));if(!row)throw new Error('预约不存在');const allowed={confirmed:['arrived','cancelled','no_show'],arrived:['completed','cancelled'],completed:[],cancelled:[],no_show:[]};if(!(allowed[row.status]||[]).includes(status))throw new Error('预约状态不能从'+row.status+'变为'+status);const before=row.status;row.status=status;audit(state,'appointment',row.id,'status',{before,after:status});if(status==='arrived'&&!state.queue.some(q=>q.appointmentId===row.id))enqueueAppointment(state,row.id);return row}
  function enqueueAppointment(state,id){const appointment=state.appointments.find(a=>a.id===Number(id)&&a.status==='arrived');if(!appointment)throw new Error('只有已到店预约才能进入轮牌');const row={id:state.nextIds.queue++,appointmentId:appointment.id,staffId:appointment.staffId,customerName:appointment.customerName,specified:appointment.specified,status:'waiting',round:1,joinedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.queue.push(row);audit(state,'queue',row.id,'enqueue',row);return row}
  function setQueueStatus(state,id,status){const row=state.queue.find(q=>q.id===Number(id));if(!row)throw new Error('轮牌记录不存在');const allowed={waiting:['serving','away'],away:['waiting'],serving:['completed'],completed:['waiting']};if(!(allowed[row.status]||[]).includes(status))throw new Error('轮牌状态不能从'+row.status+'变为'+status);const before=row.status;row.status=status;if(before==='completed'&&status==='waiting'){row.round+=1;row.joinedAt=new Date().toISOString()}row.updatedAt=new Date().toISOString();audit(state,'queue',row.id,'status',{before,after:status});return row}
  function orderedQueue(state){return state.queue.filter(q=>q.status!=='completed').slice().sort((a,b)=>Number(b.specified)-Number(a.specified)||a.joinedAt.localeCompare(b.joinedAt)||a.id-b.id)}
  function serialize(state){return JSON.stringify(state)}
  function deserialize(value){try{const parsed=JSON.parse(value);return parsed&&Array.isArray(parsed.appointments)?Object.assign(emptyState(),parsed):emptyState()}catch(_){return emptyState()}}
  return{emptyState,addStaff,addLeave,createAppointment,setAppointmentStatus,enqueueAppointment,setQueueStatus,orderedQueue,serialize,deserialize,overlaps};
});
