\set ON_ERROR_STOP on
set role service_role;
insert into public.salon_organizations(name) values('商品事务测试机构');insert into public.salon_stores(organization_id,code,name) values(1,'A','甲店'),(1,'B','乙店');
insert into public.salon_roles(organization_id,name,data_scope) values(1,'商品管理员','store');insert into public.salon_role_permissions(role_id,resource,action) values(1,'catalog','read'),(1,'catalog','write'),(1,'inventory','write');
insert into public.salon_staff(organization_id,store_id,role_id,staff_no,display_name) values(1,1,1,'A01','甲员工'),(1,2,1,'B01','乙员工');
do $$ declare first_result jsonb;retry_result jsonb;v_item bigint;blocked boolean;begin
 first_result:=public.salon_create_catalog_item(1,1,1,'catalog-create-0001','prd-01','product','洗发水','洗护',128,108,50,'瓶',null,true,3);retry_result:=public.salon_create_catalog_item(1,1,1,'catalog-create-0001','PRD-01','product','洗发水','洗护',128,108,50,'瓶',null,true,3);
 if first_result<>retry_result or (select count(*) from public.salon_catalog_items)<>1 then raise exception 'catalog idempotency failed';end if;v_item:=(first_result->>'catalogItemId')::bigint;
 if (select count(*) from public.salon_catalog_store_settings s where s.store_id=1 and s.catalog_item_id=v_item)<>1 or exists(select 1 from public.salon_catalog_store_settings s where s.store_id=2 and s.catalog_item_id=v_item) then raise exception 'catalog store isolation failed';end if;
 perform public.salon_move_inventory(1,1,1,v_item,'inventory-receive-01','receive',10,null,'采购入库');perform public.salon_move_inventory(1,1,1,v_item,'inventory-sale-0001','sale',6,null,'销售出库');
 blocked:=false;begin perform public.salon_move_inventory(1,1,1,v_item,'inventory-overdraw1','sale',5,null,'超卖');exception when others then blocked:=sqlerrm like '%库存不足%';end;if not blocked or (select quantity from public.salon_inventory_balances where store_id=1 and catalog_item_id=v_item)<>4 then raise exception 'oversell changed inventory';end if;
 blocked:=false;begin perform public.salon_move_inventory(2,1,2,v_item,'inventory-cross-001','sale',1,null,'跨店');exception when others then blocked:=sqlerrm like '%当前门店未启用%';end;if not blocked then raise exception 'cross-store inventory accepted';end if;
 perform public.salon_enable_catalog_item(2,1,2,v_item,'catalog-enable-b001',true,1);perform public.salon_move_inventory(2,1,2,v_item,'inventory-b-receive','receive',3,null,'乙店入库');if (select quantity from public.salon_inventory_balances where store_id=1 and catalog_item_id=v_item)<>4 or (select quantity from public.salon_inventory_balances where store_id=2 and catalog_item_id=v_item)<>3 then raise exception 'multi-store balances leaked';end if;
 perform public.salon_count_inventory(1,1,1,v_item,'inventory-count-001',2,'月末盘点');if (select quantity from public.salon_inventory_balances where store_id=1 and catalog_item_id=v_item)<>2 then raise exception 'inventory count failed';end if;
 if not (select low_stock from public.salon_list_catalog_inventory(1,1,1,'product','active','洗发',100) where catalog_item_id=v_item) then raise exception 'low stock warning failed';end if;
 perform public.salon_set_catalog_status(1,1,1,v_item,'catalog-disable-01','disabled','门店停售');blocked:=false;begin perform public.salon_move_inventory(1,1,1,v_item,'inventory-disabled01','sale',1,null,'停售后出库');exception when others then blocked:=sqlerrm like '%当前门店未启用%';end;if not blocked then raise exception 'disabled item moved';end if;
 if (select count(*) from public.salon_inventory_ledger where store_id=1 and catalog_item_id=v_item)<>3 or (select count(*) from public.salon_inventory_ledger where store_id=2 and catalog_item_id=v_item)<>1 then raise exception 'inventory ledger mismatch';end if;
end $$;reset role;
do $$ begin if has_table_privilege('authenticated','public.salon_catalog_store_settings','select') then raise exception 'browser catalog access';end if;if has_function_privilege('authenticated','public.salon_list_catalog_inventory(bigint,bigint,bigint,text,text,text,integer)','execute') then raise exception 'browser function access';end if;end $$;
