\set ON_ERROR_STOP on
set role service_role;
insert into public.salon_organizations(name) values('退款审批测试机构');insert into public.salon_stores(organization_id,code,name) values(1,'A','甲店'),(1,'B','乙店');insert into public.salon_roles(organization_id,name,data_scope) values(1,'申请人','store'),(1,'审批人','store');insert into public.salon_role_permissions(role_id,resource,action) values(1,'orders','refund_request'),(1,'orders','refund_read'),(1,'orders','refund_approve'),(2,'orders','refund_approve'),(2,'orders','refund_read');insert into public.salon_staff(organization_id,store_id,role_id,staff_no,display_name) values(1,1,1,'A01','申请人'),(1,1,2,'A02','审批人'),(1,2,2,'B01','乙店审批人');insert into public.salon_catalog_items(organization_id,item_type,code,name,category,list_price) values(1,'service','S1','服务','服务',100);insert into public.salon_orders(organization_id,store_id,order_no,status,subtotal,payable_total,paid_at) values(1,1,'O1','paid',200,200,now()),(1,1,'O2','paid',200,200,now());insert into public.salon_order_lines(organization_id,order_id,catalog_item_id,quantity,unit_price,line_total,item_code,item_name,item_type) values(1,1,1,2,100,200,'S1','服务','service'),(1,2,1,2,100,200,'S1','服务','service');insert into public.salon_payments(organization_id,store_id,order_id,payment_method,amount,tendered_amount,status,confirmed_at) values(1,1,1,'cash',200,200,'confirmed',now()),(1,1,2,'cash',200,200,'confirmed',now());
do $$ declare full_req jsonb;part_req jsonb;v_full bigint;v_part bigint;blocked boolean;begin full_req:=public.salon_submit_refund_request(1,1,1,1,'refund-full-apply1','full','顾客取消');v_full:=(full_req->>'refundRequestId')::bigint;if (full_req->>'requestedAmount')::numeric<>200 then raise exception 'full snapshot amount failed';end if;
 blocked:=false;begin perform public.salon_review_refund_request(1,1,1,v_full,'refund-self-review','approved','自己审批');exception when others then blocked:=sqlerrm like '%不能为同一人%';end;if not blocked then raise exception 'self approval accepted';end if;perform public.salon_review_refund_request(2,1,1,v_full,'refund-review-ok01','approved','核对通过');
 part_req:=public.salon_submit_refund_request(1,1,1,2,'refund-part-apply1','partial','部分退款','[{"orderLineId":2,"quantity":1,"amount":100}]','[{"originalPaymentId":2,"amount":100}]');v_part:=(part_req->>'refundRequestId')::bigint;blocked:=false;begin perform public.salon_submit_refund_request(1,1,1,2,'refund-part-over01','partial','超额','[{"orderLineId":2,"quantity":2,"amount":200}]','[{"originalPaymentId":2,"amount":200}]');exception when others then blocked:=sqlerrm like '%超过可退范围%';end;if not blocked then raise exception 'over refund accepted';end if;
 blocked:=false;begin perform public.salon_review_refund_request(3,1,2,v_part,'refund-cross-review','approved','跨店');exception when others then blocked:=sqlerrm like '%不存在或当前不可审批%';end;if not blocked then raise exception 'cross-store review accepted';end if;
 if (select count(*) from public.salon_payments)<>2 or exists(select 1 from public.salon_payments where reversal_of_id is not null) or (select status from public.salon_orders where id=1)<>'paid' then raise exception 'approval changed money or order';end if;
end $$;reset role;
