\set ON_ERROR_STOP on
set role service_role;
insert into public.salon_organizations(name) values('会员事务测试机构');insert into public.salon_stores(organization_id,code,name) values(1,'A','甲店'),(1,'B','乙店');insert into public.salon_roles(organization_id,name,data_scope) values(1,'会员管理员','store');insert into public.salon_role_permissions(role_id,resource,action) values(1,'members','read'),(1,'members','write'),(1,'members','recharge');insert into public.salon_staff(organization_id,store_id,role_id,staff_no,display_name) values(1,1,1,'A01','甲员工'),(1,2,1,'B01','乙员工');insert into public.salon_customers(organization_id,display_name,phone_normalized) values(1,'测试会员','13800000000');insert into public.salon_customer_store_relations(organization_id,store_id,customer_id) values(1,1,1),(1,2,1);
do $$ declare opened jsonb;retried jsonb;v_value bigint;v_times bigint;blocked boolean;begin
 opened:=public.salon_open_member_account(1,1,1,1,'member-open-value1','stored_value','SV-001','储值卡','store',current_date+365);retried:=public.salon_open_member_account(1,1,1,1,'member-open-value1','stored_value','SV-001','储值卡','store',current_date+365);if opened<>retried or (select count(*) from public.salon_member_accounts)<>1 then raise exception 'open idempotency failed';end if;v_value:=(opened->>'accountId')::bigint;
 perform public.salon_recharge_member_account(1,1,1,v_value,'member-recharge-01',500,500,50,0,'wechat','TEST-WX-1','首次充值');perform public.salon_recharge_member_account(1,1,1,v_value,'member-recharge-01',500,500,50,0,'wechat','TEST-WX-1','首次充值');if (select cash_balance from public.salon_member_accounts where id=v_value)<>500 or (select bonus_balance from public.salon_member_accounts where id=v_value)<>50 or (select count(*) from public.salon_member_recharges where account_id=v_value)<>1 then raise exception 'recharge idempotency failed';end if;
 blocked:=false;begin perform public.salon_recharge_member_account(1,1,1,v_value,'member-recharge-01',600,600,50,0,'wechat','TEST-WX-1','篡改重试');exception when others then blocked:=sqlerrm like '%幂等键已被其他业务使用%';end;if not blocked then raise exception 'changed recharge retry accepted';end if;
 blocked:=false;begin perform public.salon_recharge_member_account(2,1,2,v_value,'member-cross-store1',100,100,0,0,'cash','','跨店充值');exception when others then blocked:=sqlerrm like '%当前门店不可用%';end;if not blocked then raise exception 'store account cross-store recharge accepted';end if;
 perform public.salon_set_member_status(1,1,1,v_value,'member-freeze-001','frozen','顾客申请');blocked:=false;begin perform public.salon_recharge_member_account(1,1,1,v_value,'member-frozen-add1',100,100,0,0,'cash','','冻结充值');exception when others then blocked:=sqlerrm like '%已冻结%';end;if not blocked then raise exception 'frozen account recharged';end if;perform public.salon_set_member_status(1,1,1,v_value,'member-restore-001','active','顾客恢复');
 opened:=public.salon_open_member_account(1,1,1,1,'member-open-times1','times_card','TC-001','护理十次卡','organization',current_date+365);v_times:=(opened->>'accountId')::bigint;perform public.salon_recharge_member_account(1,1,1,v_times,'member-times-add01',300,0,0,10,'wechat','TEST-WX-2','购买十次');perform public.salon_recharge_member_account(2,1,2,v_times,'member-times-gift1',0,0,0,2,'no_payment','','跨店赠送');if (select remaining_units from public.salon_member_accounts where id=v_times)<>12 then raise exception 'times account additions failed';end if;
 blocked:=false;begin perform public.salon_recharge_member_account(1,1,1,v_value,'member-bad-money01',100,90,0,0,'cash','','金额不符');exception when others then blocked:=sqlerrm like '%金额不匹配%';end;if not blocked then raise exception 'mismatched recharge accepted';end if;
 if (select count(*) from public.salon_account_ledger where recharge_id is not null)<>3 or (select count(*) from public.salon_list_member_accounts(2,1,2,1,'active',100))<>1 then raise exception 'ledger or scope list mismatch';end if;
end $$;reset role;do $$ begin if has_table_privilege('authenticated','public.salon_member_recharges','select') then raise exception 'browser recharge access';end if;if has_function_privilege('authenticated','public.salon_list_member_accounts(bigint,bigint,bigint,bigint,text,integer)','execute') then raise exception 'browser member function access';end if;end $$;
