\set ON_ERROR_STOP on
set role service_role;
insert into public.salon_organizations(name) values('订单流程测试机构');insert into public.salon_stores(organization_id,code,name) values(1,'A','甲店'),(1,'B','乙店');insert into public.salon_roles(organization_id,name,data_scope) values(1,'开单员工','store'),(1,'折扣员工','store');insert into public.salon_role_permissions(role_id,resource,action) values(1,'orders','read'),(1,'orders','write'),(2,'orders','read'),(2,'orders','write'),(2,'orders','discount');insert into public.salon_staff(organization_id,store_id,role_id,staff_no,display_name) values(1,1,1,'A01','普通员工'),(1,1,2,'A02','店长'),(1,2,2,'B01','乙店员工');insert into public.salon_customers(organization_id,display_name) values(1,'测试顾客');insert into public.salon_customer_store_relations(organization_id,store_id,customer_id) values(1,1,1);insert into public.salon_catalog_items(organization_id,item_type,code,name,category,list_price,member_price,cost_price,unit) values(1,'service','SVC-1','剪发','剪发',180,160,20,'次'),(1,'product','PRD-1','洗发水','洗护',100,90,40,'瓶');insert into public.salon_catalog_store_settings(organization_id,store_id,catalog_item_id,stock_tracked) values(1,1,1,false),(1,1,2,true);
do $$ declare opened jsonb;retried jsonb;v_order bigint;blocked boolean;detail jsonb;begin
 opened:=public.salon_create_order(1,1,1,'order-create-00001',1,null,'到店开单');retried:=public.salon_create_order(1,1,1,'order-create-00001',1,null,'到店开单');if opened<>retried or (select count(*) from public.salon_orders)<>1 then raise exception 'order create idempotency failed';end if;v_order:=(opened->>'orderId')::bigint;
 perform public.salon_replace_order_lines(1,1,1,v_order,'order-lines-full001',jsonb_build_array(jsonb_build_object('catalogItemId',1,'quantity',1,'unitPrice',180,'staffId',1),jsonb_build_object('catalogItemId',2,'quantity',2,'unitPrice',100,'staffId',1)),'');if (select payable_total from public.salon_orders where id=v_order)<>380 or (select item_name from public.salon_order_lines where order_id=v_order and catalog_item_id=1)<>'剪发' then raise exception 'pricing or snapshot failed';end if;
 blocked:=false;begin perform public.salon_replace_order_lines(1,1,1,v_order,'order-lines-discount',jsonb_build_array(jsonb_build_object('catalogItemId',1,'quantity',1,'unitPrice',180,'discountAmount',20,'staffId',1)),'普通员工优惠');exception when others then blocked:=sqlerrm like '%没有该门店操作权限%';end;if not blocked or (select count(*) from public.salon_order_lines where order_id=v_order)<>2 then raise exception 'discount denial changed lines';end if;
 perform public.salon_replace_order_lines(2,1,1,v_order,'order-lines-manager1',jsonb_build_array(jsonb_build_object('catalogItemId',1,'quantity',1,'unitPrice',180,'discountAmount',20,'staffId',1)),'新客优惠');if (select payable_total from public.salon_orders where id=v_order)<>160 then raise exception 'approved discount failed';end if;
 perform public.salon_set_order_status(1,1,1,v_order,'order-open-status1','opened','');perform public.salon_set_order_status(1,1,1,v_order,'order-service-stat','in_service','');perform public.salon_set_order_status(1,1,1,v_order,'order-awaiting-pay','awaiting_payment','');
 blocked:=false;begin perform public.salon_replace_order_lines(2,1,1,v_order,'order-lines-late001',jsonb_build_array(jsonb_build_object('catalogItemId',1,'quantity',1)),'');exception when others then blocked:=sqlerrm like '%只有草稿%';end;if not blocked then raise exception 'non-draft lines changed';end if;
 blocked:=false;begin perform public.salon_get_order(3,1,2,v_order);exception when others then blocked:=sqlerrm like '%不属于当前门店%';end;if not blocked then raise exception 'cross-store order read accepted';end if;detail:=public.salon_get_order(1,1,1,v_order);if detail->'order'->>'status'<>'awaiting_payment' or jsonb_array_length(detail->'lines')<>1 then raise exception 'order detail mismatch';end if;
end $$;reset role;do $$ begin if has_function_privilege('authenticated','public.salon_get_order(bigint,bigint,bigint,bigint)','execute') then raise exception 'browser order function access';end if;end $$;
