\set ON_ERROR_STOP on
set role service_role;
insert into public.salon_organizations(name) values('收银闭环测试机构');insert into public.salon_stores(organization_id,code,name) values(1,'A','甲店');insert into public.salon_roles(organization_id,name,data_scope) values(1,'收银员','store');insert into public.salon_role_permissions(role_id,resource,action) values(1,'orders','checkout');insert into public.salon_staff(organization_id,store_id,role_id,staff_no,display_name) values(1,1,1,'A01','收银员');insert into public.salon_customers(organization_id,display_name,status) values(1,'测试会员','active');insert into public.salon_customer_store_relations(organization_id,store_id,customer_id) values(1,1,1);insert into public.salon_catalog_items(organization_id,item_type,code,name,category,list_price,member_price,cost_price,unit) values(1,'service','SVC-1','剪发','剪发',100,100,20,'次'),(1,'product','PRD-1','造型品','造型',50,50,20,'件');insert into public.salon_catalog_store_settings(organization_id,store_id,catalog_item_id,stock_tracked) values(1,1,1,false),(1,1,2,true);insert into public.salon_inventory_balances(organization_id,store_id,catalog_item_id,quantity) values(1,1,2,5);insert into public.salon_member_accounts(organization_id,customer_id,account_type,account_no,display_name,home_store_id,usable_scope,status,cash_balance) values(1,1,'stored_value','SV-1','储值卡',1,'store','active',200);
insert into public.salon_orders(organization_id,store_id,order_no,customer_id,status,subtotal,payable_total) values(1,1,'T-1',1,'awaiting_payment',200,200),(1,1,'T-2',1,'awaiting_payment',400,400),(1,1,'T-3',1,'awaiting_payment',100,100),(1,1,'T-4',1,'awaiting_payment',50,50);insert into public.salon_order_lines(organization_id,order_id,catalog_item_id,quantity,unit_price,line_total,item_code,item_name,item_type) values(1,1,1,1,100,100,'SVC-1','剪发','service'),(1,1,2,2,50,100,'PRD-1','造型品','product'),(1,2,2,8,50,400,'PRD-1','造型品','product'),(1,3,1,1,100,100,'SVC-1','剪发','service'),(1,4,1,1,50,50,'SVC-1','剪发','service');
do $$ declare result jsonb;retry jsonb;blocked boolean;begin
 result:=public.salon_checkout_order(1,1,1,1,'checkout-closure-01','[{"method":"member_value","amount":50,"accountId":1},{"method":"wechat","amount":50,"externalReference":"WX-TEST-1"},{"method":"cash","amount":100,"tenderedAmount":150}]');retry:=public.salon_checkout_order(1,1,1,1,'checkout-closure-01','[{"method":"member_value","amount":50,"accountId":1},{"method":"wechat","amount":50,"externalReference":"WX-TEST-1"},{"method":"cash","amount":100,"tenderedAmount":150}]');
 if result<>retry or (result->>'change')::numeric<>50 or (select cash_balance from public.salon_member_accounts where id=1)<>150 or (select quantity from public.salon_inventory_balances where catalog_item_id=2)<>3 or (select count(*) from public.salon_payments where order_id=1)<>3 then raise exception 'checkout closure mismatch';end if;
 blocked:=false;begin perform public.salon_checkout_order(1,1,1,1,'checkout-closure-01','[{"method":"cash","amount":200,"tenderedAmount":200}]');exception when others then blocked:=sqlerrm like '%幂等键已被其他业务使用%';end;if not blocked then raise exception 'changed retry accepted';end if;
 blocked:=false;begin perform public.salon_checkout_order(1,1,1,2,'checkout-stock-fail','[{"method":"cash","amount":400,"tenderedAmount":400}]');exception when others then blocked:=sqlerrm like '%库存不足%';end;if not blocked or exists(select 1 from public.salon_payments where order_id=2) or (select status from public.salon_orders where id=2)<>'awaiting_payment' or (select quantity from public.salon_inventory_balances where catalog_item_id=2)<>3 then raise exception 'stock failure did not roll back';end if;
 blocked:=false;begin perform public.salon_checkout_order(1,1,1,3,'checkout-ref-dup001','[{"method":"wechat","amount":100,"externalReference":"WX-TEST-1"}]');exception when others then blocked:=sqlerrm like '%凭证号已经使用%';end;if not blocked or exists(select 1 from public.salon_payments where order_id=3) then raise exception 'duplicate reference accepted';end if;
 update public.salon_customers set status='frozen' where id=1;blocked:=false;begin perform public.salon_checkout_order(1,1,1,4,'checkout-frozen-001','[{"method":"member_value","amount":50,"accountId":1}]');exception when others then blocked:=sqlerrm like '%顾客当前不可使用%';end;if not blocked or (select cash_balance from public.salon_member_accounts where id=1)<>150 then raise exception 'frozen customer member payment accepted';end if;
end $$;reset role;
