-- Store-scoped works, consent, reviews, tip intents, campaigns and customer booking requests.
-- Tip rows are intents only: this migration never confirms, settles or refunds money.
set statement_timeout='30s';set lock_timeout='5s';

insert into public.salon_permission_catalog(resource,action,label) values
('works','read','查看作品'),('works','write','管理作品'),('works','review','审核作品'),
('reviews','read','查看评价'),('reviews','moderate','处理评价'),
('marketing','read','查看营销活动'),('marketing','write','管理营销活动'),
('customer_portal','manage','处理顾客端预约')
on conflict(resource,action) do update set label=excluded.label;

create table public.salon_customer_auth_identities(
 id bigint generated always as identity primary key,organization_id bigint not null,customer_id bigint not null,auth_user_id uuid not null,
 status text not null default 'active' check(status in('active','disabled')),created_at timestamptz not null default now(),
 unique(organization_id,id),unique(organization_id,customer_id),unique(organization_id,auth_user_id),
 foreign key(organization_id,customer_id) references public.salon_customers(organization_id,id) on delete restrict
);

create table public.salon_customer_consents(
 id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,customer_id bigint not null,
 consent_type text not null check(consent_type in('work_publication','marketing_messages')),
 status text not null check(status in('granted','revoked')),scope_json jsonb not null default '{}' check(jsonb_typeof(scope_json)='object'),
 evidence_ref text not null check(nullif(btrim(evidence_ref),'') is not null),captured_via text not null check(captured_via in('customer_portal','signed_form')),
 granted_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,id),
 check((status='granted' and granted_at is not null and revoked_at is null)or(status='revoked' and revoked_at is not null)),
 foreign key(organization_id,store_id) references public.salon_stores(organization_id,id) on delete restrict,
 foreign key(organization_id,customer_id) references public.salon_customers(organization_id,id) on delete restrict
);
create index salon_customer_consents_lookup_idx on public.salon_customer_consents(organization_id,store_id,customer_id,consent_type,created_at desc);

create table public.salon_works(
 id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,staff_id bigint not null,customer_id bigint,
 order_id bigint,consent_id bigint,title text not null check(nullif(btrim(title),'') is not null),description text not null default '',
 asset_ref text not null check(nullif(btrim(asset_ref),'') is not null),status text not null default 'draft' check(status in('draft','pending_review','published','rejected','withdrawn')),
 submitted_at timestamptz,reviewed_by_staff_id bigint,reviewed_at timestamptz,review_reason text not null default '',published_at timestamptz,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),
 foreign key(organization_id,store_id) references public.salon_stores(organization_id,id) on delete restrict,
 foreign key(organization_id,staff_id) references public.salon_staff(organization_id,id) on delete restrict,
 foreign key(organization_id,customer_id) references public.salon_customers(organization_id,id) on delete restrict,
 foreign key(organization_id,order_id) references public.salon_orders(organization_id,id) on delete restrict,
 foreign key(organization_id,consent_id) references public.salon_customer_consents(organization_id,id) on delete restrict,
 foreign key(organization_id,reviewed_by_staff_id) references public.salon_staff(organization_id,id) on delete restrict
);
create index salon_works_store_status_idx on public.salon_works(organization_id,store_id,status,created_at desc);

create table public.salon_reviews(
 id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,order_id bigint not null,customer_id bigint not null,staff_id bigint not null,
 rating smallint not null check(rating between 1 and 5),comment text not null default '',is_anonymous boolean not null default false,
 status text not null default 'published' check(status in('published','hidden')),moderated_by_staff_id bigint,moderated_at timestamptz,moderation_reason text not null default '',
 created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,order_id,staff_id),
 foreign key(organization_id,store_id) references public.salon_stores(organization_id,id) on delete restrict,
 foreign key(organization_id,order_id) references public.salon_orders(organization_id,id) on delete restrict,
 foreign key(organization_id,customer_id) references public.salon_customers(organization_id,id) on delete restrict,
 foreign key(organization_id,staff_id) references public.salon_staff(organization_id,id) on delete restrict,
 foreign key(organization_id,moderated_by_staff_id) references public.salon_staff(organization_id,id) on delete restrict
);
create index salon_reviews_store_idx on public.salon_reviews(organization_id,store_id,status,created_at desc);

create table public.salon_tip_intents(
 id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,review_id bigint not null,customer_id bigint not null,staff_id bigint not null,
 amount numeric(12,2) not null check(amount>0),status text not null default 'pending' check(status in('pending','cancelled','confirmed','failed','refunded')),
 payment_provider text not null default '',external_reference text,confirmed_at timestamptz,created_at timestamptz not null default now(),
 unique(organization_id,id),unique(organization_id,review_id),
 foreign key(organization_id,store_id) references public.salon_stores(organization_id,id) on delete restrict,
 foreign key(organization_id,review_id) references public.salon_reviews(organization_id,id) on delete restrict,
 foreign key(organization_id,customer_id) references public.salon_customers(organization_id,id) on delete restrict,
 foreign key(organization_id,staff_id) references public.salon_staff(organization_id,id) on delete restrict
);

create table public.salon_campaigns(
 id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,name text not null check(nullif(btrim(name),'') is not null),
 channel text not null check(channel in('in_app','wechat_manual','sms_manual')),audience_json jsonb not null check(jsonb_typeof(audience_json)='object'),
 message_template text not null default '',starts_on date not null,ends_on date not null,status text not null default 'draft' check(status in('draft','active','paused','ended','cancelled')),
 created_by_staff_id bigint not null,updated_by_staff_id bigint not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(ends_on>=starts_on),unique(organization_id,id),
 foreign key(organization_id,store_id) references public.salon_stores(organization_id,id) on delete restrict,
 foreign key(organization_id,created_by_staff_id) references public.salon_staff(organization_id,id) on delete restrict,
 foreign key(organization_id,updated_by_staff_id) references public.salon_staff(organization_id,id) on delete restrict
);
create index salon_campaigns_store_status_idx on public.salon_campaigns(organization_id,store_id,status,starts_on desc);

create table public.salon_customer_booking_requests(
 id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,customer_id bigint not null,catalog_item_id bigint not null,staff_id bigint,
 starts_at timestamptz not null,ends_at timestamptz not null,notes text not null default '',status text not null default 'submitted'
 check(status in('submitted','confirmed','rejected','cancel_requested','cancelled')),appointment_id bigint,handled_by_staff_id bigint,handled_at timestamptz,handle_reason text not null default '',
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at),unique(organization_id,id),
 foreign key(organization_id,store_id) references public.salon_stores(organization_id,id) on delete restrict,
 foreign key(organization_id,customer_id) references public.salon_customers(organization_id,id) on delete restrict,
 foreign key(organization_id,catalog_item_id) references public.salon_catalog_items(organization_id,id) on delete restrict,
 foreign key(organization_id,staff_id) references public.salon_staff(organization_id,id) on delete restrict,
 foreign key(organization_id,appointment_id) references public.salon_appointments(organization_id,id) on delete restrict,
 foreign key(organization_id,handled_by_staff_id) references public.salon_staff(organization_id,id) on delete restrict
);
create index salon_customer_booking_requests_store_idx on public.salon_customer_booking_requests(organization_id,store_id,status,starts_at);

do $$declare t text;begin foreach t in array array['salon_customer_auth_identities','salon_customer_consents','salon_works','salon_reviews','salon_tip_intents','salon_campaigns','salon_customer_booking_requests'] loop
 execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);
 execute format('revoke all on table public.%I from public,anon,authenticated',t);execute format('grant all on table public.%I to service_role',t);
end loop;end$$;

alter table public.salon_operation_requests drop constraint salon_operation_requests_action_check;
alter table public.salon_operation_requests add constraint salon_operation_requests_action_check check(action in(
 'checkout','refund','inventory_move','customer_create','customer_status','customer_relation','catalog_create','catalog_enable','catalog_status','inventory_count',
 'member_open','member_recharge','member_status','order_create','order_lines','order_status','refund_request','refund_review','refund_execute','finance_entry',
 'staff_create','staff_status','commission_rule','payroll_generate','payroll_review','role_create','role_status','staff_assign','staff_transfer',
 'customer_bind','consent_set','work_create','work_submit','work_review','review_create','review_moderate','campaign_create','campaign_status','booking_request','booking_review','booking_cancel'
));

create or replace function public.salon_bind_customer_identity(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_customer_id bigint,p_auth_user_id uuid,p_request_key text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'customers','write');
 if p_auth_user_id is null or nullif(btrim(coalesce(p_reason,'')),'') is null or not exists(select 1 from public.salon_customer_store_relations where organization_id=p_organization_id and store_id=p_store_id and customer_id=p_customer_id) then raise exception '顾客端绑定参数无效';end if;
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'customer_bind','customer_bind_payload',hashtextextended(jsonb_build_object('customer',p_customer_id,'authUser',p_auth_user_id)::text,0));if v_op.completed_at is not null then return v_op.response_json;end if;
 begin insert into public.salon_customer_auth_identities(organization_id,customer_id,auth_user_id) values(p_organization_id,p_customer_id,p_auth_user_id) returning id into v_id;exception when unique_violation then raise exception '顾客或登录账号已经绑定';end;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'customer_identity',v_id::text,'bind',jsonb_build_object('customerId',p_customer_id),btrim(p_reason));
 v_response:=jsonb_build_object('identityId',v_id,'customerId',p_customer_id,'status','active');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_customer_set_consent(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_request_key text,p_consent_type text,p_granted boolean,p_scope_json jsonb,p_evidence_ref text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_identity public.salon_customer_auth_identities;v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 select i.* into v_identity from public.salon_customer_auth_identities i join public.salon_customers c on c.organization_id=i.organization_id and c.id=i.customer_id and c.status='active' where i.organization_id=p_organization_id and i.auth_user_id=p_auth_user_id and i.status='active';if not found then raise exception '顾客端账号未绑定或已停用';end if;
 if p_consent_type not in('work_publication','marketing_messages') or jsonb_typeof(coalesce(p_scope_json,'{}'))<>'object' or nullif(btrim(coalesce(p_evidence_ref,'')),'') is null then raise exception '授权参数无效';end if;
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'consent_set','consent_payload',hashtextextended(jsonb_build_object('customer',v_identity.customer_id,'type',p_consent_type,'granted',p_granted,'scope',p_scope_json,'evidence',btrim(p_evidence_ref))::text,0));if v_op.completed_at is not null then return v_op.response_json;end if;
 if not exists(select 1 from public.salon_stores where organization_id=p_organization_id and id=p_store_id and status='active') then raise exception '门店不存在或已停用';end if;
 if not p_granted and p_consent_type='work_publication' then update public.salon_works set status='withdrawn',updated_at=now(),review_reason='顾客撤回公开授权' where organization_id=p_organization_id and store_id=p_store_id and customer_id=v_identity.customer_id and status in('pending_review','published');end if;
 insert into public.salon_customer_consents(organization_id,store_id,customer_id,consent_type,status,scope_json,evidence_ref,captured_via,granted_at,revoked_at) values(p_organization_id,p_store_id,v_identity.customer_id,p_consent_type,case when p_granted then 'granted' else 'revoked' end,coalesce(p_scope_json,'{}'),btrim(p_evidence_ref),'customer_portal',case when p_granted then now() end,case when not p_granted then now() end) returning id into v_id;
 insert into public.salon_audit_events(organization_id,store_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,'customer_consent',v_id::text,case when p_granted then 'grant' else 'revoke' end,jsonb_build_object('customerId',v_identity.customer_id,'type',p_consent_type),case when p_granted then '顾客端授权' else '顾客端撤回授权' end);
 v_response:=jsonb_build_object('consentId',v_id,'customerId',v_identity.customer_id,'status',case when p_granted then 'granted' else 'revoked' end);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_create_work(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_request_key text,p_customer_id bigint,p_order_id bigint,p_consent_id bigint,p_title text,p_description text,p_asset_ref text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','write');
 if nullif(btrim(coalesce(p_title,'')),'') is null or nullif(btrim(coalesce(p_asset_ref,'')),'') is null or not exists(select 1 from public.salon_staff where organization_id=p_organization_id and id=p_actor_staff_id and employment_status='active') or (p_customer_id is not null and not exists(select 1 from public.salon_customer_store_relations where organization_id=p_organization_id and store_id=p_store_id and customer_id=p_customer_id)) or (p_order_id is not null and not exists(select 1 from public.salon_orders where organization_id=p_organization_id and store_id=p_store_id and id=p_order_id and (p_customer_id is null or customer_id=p_customer_id))) then raise exception '作品参数无效';end if;
 if p_consent_id is not null and not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.store_id=p_store_id and c.id=p_consent_id and c.customer_id=p_customer_id and c.consent_type='work_publication' and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type=c.consent_type and r.status='revoked' and r.id>c.id)) then raise exception '作品公开授权无效或已撤回';end if;
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'work_create','work_payload',hashtextextended(jsonb_build_object('staff',p_actor_staff_id,'customer',p_customer_id,'order',p_order_id,'title',btrim(p_title),'asset',btrim(p_asset_ref))::text,0));if v_op.completed_at is not null then return v_op.response_json;end if;
 insert into public.salon_works(organization_id,store_id,staff_id,customer_id,order_id,consent_id,title,description,asset_ref) values(p_organization_id,p_store_id,p_actor_staff_id,p_customer_id,p_order_id,p_consent_id,btrim(p_title),coalesce(p_description,''),btrim(p_asset_ref)) returning id into v_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'work',v_id::text,'create',jsonb_build_object('title',btrim(p_title),'customerId',p_customer_id,'orderId',p_order_id),'创建作品草稿');
 v_response:=jsonb_build_object('workId',v_id,'status','draft');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_submit_work(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_work_id bigint,p_request_key text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v public.salon_works;v_op public.salon_operation_requests;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','write');v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'work_submit','work',p_work_id);if v_op.completed_at is not null then return v_op.response_json;end if;
 select * into v from public.salon_works where organization_id=p_organization_id and store_id=p_store_id and id=p_work_id for update;if not found or v.staff_id<>p_actor_staff_id or v.status<>'draft' then raise exception '作品不存在、非本人作品或状态不能提交';end if;
 if v.customer_id is not null and (v.consent_id is null or not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.id=v.consent_id and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type='work_publication' and r.status='revoked' and r.id>c.id))) then raise exception '未取得有效顾客公开授权';end if;
 update public.salon_works set status='pending_review',submitted_at=now(),updated_at=now() where organization_id=p_organization_id and id=p_work_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'work',p_work_id::text,'submit',jsonb_build_object('status','pending_review'),'提交作品审核');v_response:=jsonb_build_object('workId',p_work_id,'status','pending_review');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_review_work(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_work_id bigint,p_request_key text,p_decision text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v public.salon_works;v_op public.salon_operation_requests;v_status text;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','review');if p_decision not in('published','rejected') or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '作品审核决定或说明无效';end if;
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'work_review','work',p_work_id);if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_works where organization_id=p_organization_id and store_id=p_store_id and id=p_work_id for update;if not found or v.status<>'pending_review' then raise exception '作品不存在或不在待审核状态';end if;if p_decision='published' and v.customer_id is not null and (v.consent_id is null or not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.id=v.consent_id and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type='work_publication' and r.status='revoked' and r.id>c.id))) then raise exception '顾客公开授权无效或已撤回';end if;
 v_status:=p_decision;update public.salon_works set status=v_status,reviewed_by_staff_id=p_actor_staff_id,reviewed_at=now(),review_reason=btrim(p_reason),published_at=case when v_status='published' then now() end,updated_at=now() where organization_id=p_organization_id and id=p_work_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'work',p_work_id::text,'review',jsonb_build_object('status',v.status),jsonb_build_object('status',v_status),btrim(p_reason));v_response:=jsonb_build_object('workId',p_work_id,'status',v_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_customer_create_review(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_request_key text,p_order_id bigint,p_staff_id bigint,p_rating integer,p_comment text,p_is_anonymous boolean,p_tip_amount numeric)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_identity public.salon_customer_auth_identities;v_order public.salon_orders;v_op public.salon_operation_requests;v_id bigint;v_tip_id bigint;v_response jsonb;begin
 select * into v_identity from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active';if not found then raise exception '顾客端账号未绑定或已停用';end if;if p_rating not between 1 and 5 or p_tip_amount is null or p_tip_amount<0 then raise exception '评分或打赏意向金额无效';end if;
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'review_create','review_payload',hashtextextended(jsonb_build_object('order',p_order_id,'staff',p_staff_id,'rating',p_rating,'comment',coalesce(p_comment,''),'anonymous',coalesce(p_is_anonymous,false),'tip',round(p_tip_amount,2))::text,0));if v_op.completed_at is not null then return v_op.response_json;end if;select * into v_order from public.salon_orders where organization_id=p_organization_id and store_id=p_store_id and id=p_order_id and customer_id=v_identity.customer_id and status='paid' for update;if not found or not exists(select 1 from public.salon_order_lines where organization_id=p_organization_id and order_id=p_order_id and staff_id=p_staff_id and service_status<>'cancelled') then raise exception '仅订单本人可评价已完成服务人员';end if;
 begin insert into public.salon_reviews(organization_id,store_id,order_id,customer_id,staff_id,rating,comment,is_anonymous) values(p_organization_id,p_store_id,p_order_id,v_identity.customer_id,p_staff_id,p_rating,coalesce(p_comment,''),coalesce(p_is_anonymous,false)) returning id into v_id;exception when unique_violation then raise exception '该订单已经评价过此服务人员';end;
 if p_tip_amount>0 then insert into public.salon_tip_intents(organization_id,store_id,review_id,customer_id,staff_id,amount) values(p_organization_id,p_store_id,v_id,v_identity.customer_id,p_staff_id,round(p_tip_amount,2)) returning id into v_tip_id;end if;
 insert into public.salon_audit_events(organization_id,store_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,'review',v_id::text,'create',jsonb_build_object('orderId',p_order_id,'staffId',p_staff_id,'rating',p_rating,'tipIntentId',v_tip_id),'顾客端评价');v_response:=jsonb_build_object('reviewId',v_id,'status','published','tipIntentId',v_tip_id,'tipStatus',case when v_tip_id is null then null else 'pending' end);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_moderate_review(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_review_id bigint,p_request_key text,p_status text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v public.salon_reviews;v_op public.salon_operation_requests;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'reviews','moderate');if p_status not in('published','hidden') or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '评价处理状态或原因无效';end if;v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'review_moderate','review',p_review_id);if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_reviews where organization_id=p_organization_id and store_id=p_store_id and id=p_review_id for update;if not found or v.status=p_status then raise exception '评价不存在或已经是目标状态';end if;update public.salon_reviews set status=p_status,moderated_by_staff_id=p_actor_staff_id,moderated_at=now(),moderation_reason=btrim(p_reason) where organization_id=p_organization_id and id=p_review_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'review',p_review_id::text,'moderate',jsonb_build_object('status',v.status),jsonb_build_object('status',p_status),btrim(p_reason));v_response:=jsonb_build_object('reviewId',p_review_id,'status',p_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_create_campaign(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_request_key text,p_name text,p_channel text,p_audience_json jsonb,p_message_template text,p_starts_on date,p_ends_on date)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'marketing','write');if nullif(btrim(coalesce(p_name,'')),'') is null or p_channel not in('in_app','wechat_manual','sms_manual') or jsonb_typeof(coalesce(p_audience_json,'{}'))<>'object' or p_starts_on is null or p_ends_on<p_starts_on then raise exception '营销活动参数无效';end if;v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'campaign_create','campaign_payload',hashtextextended(jsonb_build_object('name',btrim(p_name),'channel',p_channel,'starts',p_starts_on,'ends',p_ends_on)::text,0));if v_op.completed_at is not null then return v_op.response_json;end if;insert into public.salon_campaigns(organization_id,store_id,name,channel,audience_json,message_template,starts_on,ends_on,created_by_staff_id,updated_by_staff_id) values(p_organization_id,p_store_id,btrim(p_name),p_channel,p_audience_json,coalesce(p_message_template,''),p_starts_on,p_ends_on,p_actor_staff_id,p_actor_staff_id) returning id into v_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'campaign',v_id::text,'create',jsonb_build_object('name',btrim(p_name),'channel',p_channel,'startsOn',p_starts_on,'endsOn',p_ends_on),'创建营销活动草稿');v_response:=jsonb_build_object('campaignId',v_id,'status','draft');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_set_campaign_status(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_campaign_id bigint,p_request_key text,p_status text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v public.salon_campaigns;v_op public.salon_operation_requests;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'marketing','write');if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '活动状态变更原因不能为空';end if;v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'campaign_status','campaign',p_campaign_id);if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_campaigns where organization_id=p_organization_id and store_id=p_store_id and id=p_campaign_id for update;if not found or not((v.status='draft' and p_status in('active','cancelled'))or(v.status='active' and p_status in('paused','ended','cancelled'))or(v.status='paused' and p_status in('active','ended','cancelled'))) then raise exception '活动不存在或状态变更无效';end if;if p_status='active' and not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.store_id=p_store_id and c.consent_type='marketing_messages' and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type=c.consent_type and r.status='revoked' and r.id>c.id)) then raise exception '当前门店没有有效营销授权顾客，不能启用活动';end if;update public.salon_campaigns set status=p_status,updated_by_staff_id=p_actor_staff_id,updated_at=now() where organization_id=p_organization_id and id=p_campaign_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'campaign',p_campaign_id::text,'status',jsonb_build_object('status',v.status),jsonb_build_object('status',p_status),btrim(p_reason));v_response:=jsonb_build_object('campaignId',p_campaign_id,'status',p_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_customer_request_booking(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_request_key text,p_catalog_item_id bigint,p_staff_id bigint,p_starts_at timestamptz,p_ends_at timestamptz,p_notes text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_identity public.salon_customer_auth_identities;v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 select * into v_identity from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active';if not found then raise exception '顾客端账号未绑定或已停用';end if;if p_ends_at<=p_starts_at or p_starts_at<now() or not exists(select 1 from public.salon_catalog_items i join public.salon_catalog_store_settings s on s.organization_id=i.organization_id and s.catalog_item_id=i.id where i.organization_id=p_organization_id and i.id=p_catalog_item_id and i.item_type='service' and i.status='active' and s.store_id=p_store_id and s.status='active') or (p_staff_id is not null and not exists(select 1 from public.salon_staff where organization_id=p_organization_id and store_id=p_store_id and id=p_staff_id and employment_status='active')) then raise exception '自助预约项目、手艺人或时间无效';end if;
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'booking_request','booking_payload',hashtextextended(jsonb_build_object('customer',v_identity.customer_id,'catalogItem',p_catalog_item_id,'staff',p_staff_id,'startsAt',p_starts_at,'endsAt',p_ends_at,'notes',coalesce(p_notes,''))::text,0));if v_op.completed_at is not null then return v_op.response_json;end if;insert into public.salon_customer_store_relations(organization_id,store_id,customer_id,source) values(p_organization_id,p_store_id,v_identity.customer_id,'customer_portal') on conflict(store_id,customer_id) do nothing;insert into public.salon_customer_booking_requests(organization_id,store_id,customer_id,catalog_item_id,staff_id,starts_at,ends_at,notes) values(p_organization_id,p_store_id,v_identity.customer_id,p_catalog_item_id,p_staff_id,p_starts_at,p_ends_at,coalesce(p_notes,'')) returning id into v_id;insert into public.salon_audit_events(organization_id,store_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,'customer_booking',v_id::text,'submit',jsonb_build_object('customerId',v_identity.customer_id,'catalogItemId',p_catalog_item_id,'staffId',p_staff_id,'startsAt',p_starts_at,'endsAt',p_ends_at),'顾客端提交预约');v_response:=jsonb_build_object('bookingRequestId',v_id,'status','submitted');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_review_customer_booking(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_booking_request_id bigint,p_request_key text,p_decision text,p_staff_id bigint,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v public.salon_customer_booking_requests;v_op public.salon_operation_requests;v_result jsonb;v_appointment_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'customer_portal','manage');if p_decision not in('confirmed','rejected') or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '预约处理决定或原因无效';end if;v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'booking_review','booking_request',p_booking_request_id);if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_customer_booking_requests where organization_id=p_organization_id and store_id=p_store_id and id=p_booking_request_id for update;if not found or v.status<>'submitted' then raise exception '预约申请不存在或已经处理';end if;if p_decision='confirmed' then v_result:=public.salon_create_appointment(p_actor_staff_id,p_organization_id,p_store_id,coalesce(p_staff_id,v.staff_id),v.customer_id,v.starts_at,v.ends_at,'customer_portal',v.notes);v_appointment_id:=(v_result->>'appointmentId')::bigint;end if;update public.salon_customer_booking_requests set status=p_decision,appointment_id=v_appointment_id,staff_id=coalesce(p_staff_id,staff_id),handled_by_staff_id=p_actor_staff_id,handled_at=now(),handle_reason=btrim(p_reason),updated_at=now() where organization_id=p_organization_id and id=p_booking_request_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'customer_booking',p_booking_request_id::text,'review',jsonb_build_object('status',v.status),jsonb_build_object('status',p_decision,'appointmentId',v_appointment_id),btrim(p_reason));v_response:=jsonb_build_object('bookingRequestId',p_booking_request_id,'status',p_decision,'appointmentId',v_appointment_id);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_customer_request_booking_cancel(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_booking_request_id bigint,p_request_key text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $$declare v_identity public.salon_customer_auth_identities;v public.salon_customer_booking_requests;v_op public.salon_operation_requests;v_status text;v_response jsonb;begin
 select * into v_identity from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active';if not found or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '取消预约参数无效';end if;v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'booking_cancel','booking_request',p_booking_request_id);if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_customer_booking_requests where organization_id=p_organization_id and store_id=p_store_id and id=p_booking_request_id and customer_id=v_identity.customer_id for update;if not found or v.status not in('submitted','confirmed') then raise exception '预约申请不存在或当前不能取消';end if;v_status:=case when v.status='submitted' then 'cancelled' else 'cancel_requested' end;update public.salon_customer_booking_requests set status=v_status,handle_reason=btrim(p_reason),updated_at=now() where organization_id=p_organization_id and id=p_booking_request_id;insert into public.salon_audit_events(organization_id,store_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,'customer_booking',p_booking_request_id::text,'cancel_request',jsonb_build_object('status',v.status),jsonb_build_object('status',v_status),btrim(p_reason));v_response:=jsonb_build_object('bookingRequestId',p_booking_request_id,'status',v_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;

create or replace function public.salon_list_works(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_status text default '',p_limit integer default 200) returns setof public.salon_works language plpgsql security invoker set search_path='' as $$begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','read');if p_limit not between 1 and 500 then raise exception '作品查询数量无效';end if;return query select * from public.salon_works where organization_id=p_organization_id and store_id=p_store_id and(coalesce(p_status,'')='' or status=p_status) order by created_at desc,id desc limit p_limit;end$$;
create or replace function public.salon_list_reviews(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_status text default '',p_limit integer default 200) returns setof public.salon_reviews language plpgsql security invoker set search_path='' as $$begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'reviews','read');if p_limit not between 1 and 500 then raise exception '评价查询数量无效';end if;return query select * from public.salon_reviews where organization_id=p_organization_id and store_id=p_store_id and(coalesce(p_status,'')='' or status=p_status) order by created_at desc,id desc limit p_limit;end$$;
create or replace function public.salon_list_campaigns(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_status text default '',p_limit integer default 200) returns setof public.salon_campaigns language plpgsql security invoker set search_path='' as $$begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'marketing','read');if p_limit not between 1 and 500 then raise exception '活动查询数量无效';end if;return query select * from public.salon_campaigns where organization_id=p_organization_id and store_id=p_store_id and(coalesce(p_status,'')='' or status=p_status) order by starts_on desc,id desc limit p_limit;end$$;
create or replace function public.salon_list_customer_bookings(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_status text default '',p_limit integer default 200) returns setof public.salon_customer_booking_requests language plpgsql security invoker set search_path='' as $$begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'customer_portal','manage');if p_limit not between 1 and 500 then raise exception '预约申请查询数量无效';end if;return query select * from public.salon_customer_booking_requests where organization_id=p_organization_id and store_id=p_store_id and(coalesce(p_status,'')='' or status=p_status) order by created_at desc,id desc limit p_limit;end$$;
create or replace function public.salon_customer_list_public_works(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_limit integer default 100) returns table(id bigint,title text,description text,asset_ref text,staff_id bigint,published_at timestamptz) language plpgsql security invoker set search_path='' as $$begin if not exists(select 1 from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active') or p_limit not between 1 and 200 then raise exception '顾客端身份或查询数量无效';end if;return query select w.id,w.title,w.description,w.asset_ref,w.staff_id,w.published_at from public.salon_works w where w.organization_id=p_organization_id and w.store_id=p_store_id and w.status='published' order by w.published_at desc,w.id desc limit p_limit;end$$;
create or replace function public.salon_customer_list_bookings(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_limit integer default 100) returns setof public.salon_customer_booking_requests language plpgsql security invoker set search_path='' as $$declare v_customer bigint;begin select customer_id into v_customer from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active';if not found or p_limit not between 1 and 200 then raise exception '顾客端身份或查询数量无效';end if;return query select * from public.salon_customer_booking_requests where organization_id=p_organization_id and store_id=p_store_id and customer_id=v_customer order by created_at desc,id desc limit p_limit;end$$;
create or replace function public.salon_customer_get_context(p_auth_user_id uuid) returns jsonb language plpgsql security invoker set search_path='' as $$declare v_result jsonb;begin select jsonb_agg(jsonb_build_object('organizationId',i.organization_id,'customerId',i.customer_id,'displayName',c.display_name,'stores',coalesce((select jsonb_agg(jsonb_build_object('storeId',s.id,'code',s.code,'name',s.name) order by s.id) from public.salon_stores s where s.organization_id=i.organization_id and s.status='active'),'[]'::jsonb)) order by i.organization_id) into v_result from public.salon_customer_auth_identities i join public.salon_customers c on c.organization_id=i.organization_id and c.id=i.customer_id and c.status='active' where i.auth_user_id=p_auth_user_id and i.status='active';if v_result is null then raise exception '顾客端账号未绑定或已停用';end if;return v_result;end$$;
create or replace function public.salon_customer_list_booking_options(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint) returns jsonb language plpgsql security invoker set search_path='' as $$declare v_result jsonb;begin if not exists(select 1 from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active') or not exists(select 1 from public.salon_stores where organization_id=p_organization_id and id=p_store_id and status='active') then raise exception '顾客端身份或门店无效';end if;select jsonb_build_object('services',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'code',i.code,'name',i.name,'category',i.category,'price',case when i.member_price>0 then i.member_price else i.list_price end,'durationMinutes',i.duration_minutes) order by i.category,i.name) from public.salon_catalog_items i join public.salon_catalog_store_settings s on s.organization_id=i.organization_id and s.catalog_item_id=i.id and s.store_id=p_store_id and s.status='active' where i.organization_id=p_organization_id and i.item_type='service' and i.status='active'),'[]'::jsonb),'staff',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'displayName',x.display_name,'position',x.position,'levelName',x.level_name) order by x.display_name) from public.salon_staff x where x.organization_id=p_organization_id and x.store_id=p_store_id and x.employment_status='active'),'[]'::jsonb)) into v_result;return v_result;end$$;

do $$declare sig text;begin foreach sig in array array[
 'public.salon_bind_customer_identity(bigint,bigint,bigint,bigint,uuid,text,text)','public.salon_customer_set_consent(uuid,bigint,bigint,text,text,boolean,jsonb,text)',
 'public.salon_create_work(bigint,bigint,bigint,text,bigint,bigint,bigint,text,text,text)','public.salon_submit_work(bigint,bigint,bigint,bigint,text)','public.salon_review_work(bigint,bigint,bigint,bigint,text,text,text)',
 'public.salon_customer_create_review(uuid,bigint,bigint,text,bigint,bigint,integer,text,boolean,numeric)','public.salon_moderate_review(bigint,bigint,bigint,bigint,text,text,text)',
 'public.salon_create_campaign(bigint,bigint,bigint,text,text,text,jsonb,text,date,date)','public.salon_set_campaign_status(bigint,bigint,bigint,bigint,text,text,text)',
 'public.salon_customer_request_booking(uuid,bigint,bigint,text,bigint,bigint,timestamptz,timestamptz,text)','public.salon_review_customer_booking(bigint,bigint,bigint,bigint,text,text,bigint,text)',
 'public.salon_customer_request_booking_cancel(uuid,bigint,bigint,bigint,text,text)','public.salon_list_works(bigint,bigint,bigint,text,integer)','public.salon_list_reviews(bigint,bigint,bigint,text,integer)',
 'public.salon_list_campaigns(bigint,bigint,bigint,text,integer)','public.salon_list_customer_bookings(bigint,bigint,bigint,text,integer)','public.salon_customer_list_public_works(uuid,bigint,bigint,integer)','public.salon_customer_list_bookings(uuid,bigint,bigint,integer)',
 'public.salon_customer_get_context(uuid)','public.salon_customer_list_booking_options(uuid,bigint,bigint)'
 ] loop execute 'revoke execute on function '||sig||' from public,anon,authenticated';execute 'grant execute on function '||sig||' to service_role';end loop;end$$;

comment on table public.salon_tip_intents is 'Non-financial customer intent only. Pending rows must never be counted as payment, revenue or payroll.';
comment on table public.salon_customer_consents is 'Audited customer consent evidence; publication and marketing must check the latest revocation.';
