-- Maker-checker refund requests. Approval never moves money or stock.
set statement_timeout='30s';set lock_timeout='5s';
create table public.salon_refund_requests(id bigint generated always as identity primary key,organization_id bigint not null,store_id bigint not null,order_id bigint not null,refund_type text not null check(refund_type in ('full','partial')),status text not null default 'submitted' check(status in ('submitted','approved','rejected','executed','cancelled')),requested_amount numeric(12,2) not null check(requested_amount>=0),reason text not null,created_by_staff_id bigint not null,reviewed_by_staff_id bigint,decision_reason text not null default '',created_at timestamptz not null default now(),reviewed_at timestamptz,executed_at timestamptz,unique(organization_id,id),foreign key(organization_id,store_id) references public.salon_stores(organization_id,id),foreign key(organization_id,order_id) references public.salon_orders(organization_id,id),foreign key(organization_id,created_by_staff_id) references public.salon_staff(organization_id,id),foreign key(organization_id,reviewed_by_staff_id) references public.salon_staff(organization_id,id));
create index salon_refund_requests_scope_idx on public.salon_refund_requests(organization_id,store_id,status,created_at desc);
create table public.salon_refund_request_lines(organization_id bigint not null,refund_request_id bigint not null,order_line_id bigint not null,quantity numeric(12,3) not null check(quantity>0),refund_amount numeric(12,2) not null check(refund_amount>0),item_code text not null,item_name text not null,item_type text not null,primary key(refund_request_id,order_line_id),foreign key(organization_id,refund_request_id) references public.salon_refund_requests(organization_id,id),foreign key(organization_id,order_line_id) references public.salon_order_lines(organization_id,id));
create table public.salon_refund_request_payments(organization_id bigint not null,refund_request_id bigint not null,original_payment_id bigint not null,refund_amount numeric(12,2) not null check(refund_amount>0),refund_units numeric(12,3) not null default 0 check(refund_units>=0),payment_method text not null,primary key(refund_request_id,original_payment_id),foreign key(organization_id,refund_request_id) references public.salon_refund_requests(organization_id,id),foreign key(organization_id,original_payment_id) references public.salon_payments(organization_id,id));
do $$ declare t text;begin foreach t in array array['salon_refund_requests','salon_refund_request_lines','salon_refund_request_payments'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('revoke all on table public.%I from public,anon,authenticated',t);execute format('grant all on table public.%I to service_role',t);end loop;end $$;
alter table public.salon_operation_requests drop constraint salon_operation_requests_action_check;alter table public.salon_operation_requests add constraint salon_operation_requests_action_check check(action in ('checkout','refund','inventory_move','customer_create','customer_status','customer_relation','catalog_create','catalog_enable','catalog_status','inventory_count','member_open','member_recharge','member_status','order_create','order_lines','order_status','refund_request','refund_review'));

create or replace function public.salon_submit_refund_request(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_order_id bigint,p_request_key text,p_refund_type text,p_reason text,p_lines jsonb default '[]',p_payments jsonb default '[]') returns jsonb language plpgsql security invoker set search_path='' as $$
declare v_req public.salon_operation_requests;v_order public.salon_orders;v_id bigint;v_row jsonb;v_line public.salon_order_lines;v_payment public.salon_payments;v_qty numeric;v_amount numeric;v_units numeric;v_line_total numeric:=0;v_payment_total numeric:=0;v_used numeric;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','refund_request');if p_refund_type not in ('full','partial') or nullif(btrim(p_reason),'') is null then raise exception '退款类型或原因无效';end if;
 v_req:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'refund_request','refund_request_payload',hashtextextended(jsonb_build_object('order',p_order_id,'type',p_refund_type,'reason',btrim(p_reason),'lines',p_lines,'payments',p_payments)::text,0));if v_req.completed_at is not null then return v_req.response_json;end if;
 select * into v_order from public.salon_orders where organization_id=p_organization_id and store_id=p_store_id and id=p_order_id for update;if not found or v_order.status<>'paid' then raise exception '只有当前门店已支付订单可以申请退款';end if;
 insert into public.salon_refund_requests(organization_id,store_id,order_id,refund_type,requested_amount,reason,created_by_staff_id) values(p_organization_id,p_store_id,p_order_id,p_refund_type,0,btrim(p_reason),p_actor_staff_id) returning id into v_id;
 if p_refund_type='full' then
  if exists(select 1 from public.salon_refund_requests r where r.organization_id=p_organization_id and r.order_id=p_order_id and r.id<>v_id and r.status in ('submitted','approved','executed')) then raise exception '订单已有未结束退款申请';end if;
  insert into public.salon_refund_request_lines(organization_id,refund_request_id,order_line_id,quantity,refund_amount,item_code,item_name,item_type) select p_organization_id,v_id,l.id,l.quantity,l.line_total,l.item_code,l.item_name,l.item_type from public.salon_order_lines l where l.organization_id=p_organization_id and l.order_id=p_order_id;v_line_total:=v_order.payable_total;
  insert into public.salon_refund_request_payments(organization_id,refund_request_id,original_payment_id,refund_amount,refund_units,payment_method) select p_organization_id,v_id,p.id,p.amount,p.member_units,p.payment_method from public.salon_payments p where p.organization_id=p_organization_id and p.order_id=p_order_id and p.reversal_of_id is null;v_payment_total:=v_order.payable_total;
 else
  if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 or jsonb_typeof(p_payments)<>'array' or jsonb_array_length(p_payments)=0 then raise exception '部分退款必须填写商品项目和原支付分配';end if;
  for v_row in select value from jsonb_array_elements(p_lines) loop select * into v_line from public.salon_order_lines where organization_id=p_organization_id and order_id=p_order_id and id=nullif(v_row->>'orderLineId','')::bigint;if not found then raise exception '退款明细不属于原订单';end if;v_qty:=round(coalesce(nullif(v_row->>'quantity','')::numeric,0),3);v_amount:=round(coalesce(nullif(v_row->>'amount','')::numeric,0),2);select coalesce(sum(x.quantity),0),coalesce(sum(x.refund_amount),0) into v_used,v_payment_total from public.salon_refund_request_lines x join public.salon_refund_requests r on r.organization_id=x.organization_id and r.id=x.refund_request_id where x.organization_id=p_organization_id and r.order_id=p_order_id and x.order_line_id=v_line.id and r.status in ('submitted','approved','executed');if v_qty<=0 or v_amount<=0 or v_qty+v_used>v_line.quantity or v_amount+v_payment_total>v_line.line_total then raise exception '退款数量或金额超过可退范围';end if;insert into public.salon_refund_request_lines values(p_organization_id,v_id,v_line.id,v_qty,v_amount,v_line.item_code,v_line.item_name,v_line.item_type);v_line_total:=v_line_total+v_amount;end loop;
  v_payment_total:=0;for v_row in select value from jsonb_array_elements(p_payments) loop select * into v_payment from public.salon_payments where organization_id=p_organization_id and order_id=p_order_id and id=nullif(v_row->>'originalPaymentId','')::bigint and reversal_of_id is null;if not found then raise exception '退款支付分配不属于原订单';end if;v_amount:=round(coalesce(nullif(v_row->>'amount','')::numeric,0),2);v_units:=round(coalesce(nullif(v_row->>'units','')::numeric,0),3);select coalesce(sum(x.refund_amount),0) into v_used from public.salon_refund_request_payments x join public.salon_refund_requests r on r.organization_id=x.organization_id and r.id=x.refund_request_id where x.organization_id=p_organization_id and r.order_id=p_order_id and x.original_payment_id=v_payment.id and r.status in ('submitted','approved','executed');if v_amount<=0 or v_amount+v_used>v_payment.amount or (v_payment.payment_method='member_units' and (v_units<=0 or v_units>v_payment.member_units)) then raise exception '退款支付金额或次数超过可退范围';end if;insert into public.salon_refund_request_payments values(p_organization_id,v_id,v_payment.id,v_amount,v_units,v_payment.payment_method);v_payment_total:=v_payment_total+v_amount;end loop;
  if round(v_line_total,2)<>round(v_payment_total,2) then raise exception '退款明细金额必须等于原支付分配金额';end if;
 end if;
 update public.salon_refund_requests set requested_amount=round(v_line_total,2) where id=v_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'refund_request',v_id::text,'submit',jsonb_build_object('orderId',p_order_id,'type',p_refund_type,'amount',round(v_line_total,2)),btrim(p_reason));v_response:=jsonb_build_object('refundRequestId',v_id,'status','submitted','requestedAmount',round(v_line_total,2));update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_req.id;return v_response;
end $$;

create or replace function public.salon_review_refund_request(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_refund_request_id bigint,p_request_key text,p_decision text,p_reason text) returns jsonb language plpgsql security invoker set search_path='' as $$ declare v_req public.salon_operation_requests;v_refund public.salon_refund_requests;v_response jsonb;begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','refund_approve');if p_decision not in ('approved','rejected') or nullif(btrim(p_reason),'') is null then raise exception '审批决定或意见无效';end if;v_req:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'refund_review','refund_'||p_decision,p_refund_request_id);if v_req.completed_at is not null then return v_req.response_json;end if;select * into v_refund from public.salon_refund_requests where organization_id=p_organization_id and store_id=p_store_id and id=p_refund_request_id for update;if not found or v_refund.status<>'submitted' then raise exception '退款申请不存在或当前不可审批';end if;if v_refund.created_by_staff_id=p_actor_staff_id then raise exception '退款申请人与审批人不能为同一人';end if;update public.salon_refund_requests set status=p_decision,reviewed_by_staff_id=p_actor_staff_id,decision_reason=btrim(p_reason),reviewed_at=now() where id=p_refund_request_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'refund_request',p_refund_request_id::text,'review',jsonb_build_object('status','submitted'),jsonb_build_object('status',p_decision),btrim(p_reason));v_response:=jsonb_build_object('refundRequestId',p_refund_request_id,'status',p_decision);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_req.id;return v_response;end $$;

create or replace function public.salon_list_refund_requests(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_status text default '',p_limit integer default 200) returns setof public.salon_refund_requests language plpgsql security invoker set search_path='' as $$ begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','refund_read');if p_status not in ('','submitted','approved','rejected','executed','cancelled') or p_limit not between 1 and 500 then raise exception '退款查询参数无效';end if;return query select * from public.salon_refund_requests r where r.organization_id=p_organization_id and r.store_id=p_store_id and (p_status='' or r.status=p_status) order by r.created_at desc limit p_limit;end $$;
revoke execute on function public.salon_submit_refund_request(bigint,bigint,bigint,bigint,text,text,text,jsonb,jsonb) from public,anon,authenticated;revoke execute on function public.salon_review_refund_request(bigint,bigint,bigint,bigint,text,text,text) from public,anon,authenticated;revoke execute on function public.salon_list_refund_requests(bigint,bigint,bigint,text,integer) from public,anon,authenticated;grant execute on function public.salon_submit_refund_request(bigint,bigint,bigint,bigint,text,text,text,jsonb,jsonb) to service_role;grant execute on function public.salon_review_refund_request(bigint,bigint,bigint,bigint,text,text,text) to service_role;grant execute on function public.salon_list_refund_requests(bigint,bigint,bigint,text,integer) to service_role;
