-- Cashier closure: payment evidence, change, member/customer guards and
-- automatic product stock deduction in one transaction. Development only.
set statement_timeout='30s';set lock_timeout='5s';
alter table public.salon_payments add column tendered_amount numeric(12,2),add column change_amount numeric(12,2) not null default 0 check(change_amount>=0),add column external_reference text not null default '';
update public.salon_payments set tendered_amount=amount where tendered_amount is null;
alter table public.salon_payments alter column tendered_amount set not null,alter column tendered_amount set default 0,add constraint salon_payments_tendered_check check(reversal_of_id is not null or tendered_amount>=amount);
create unique index salon_payments_external_reference_idx on public.salon_payments(organization_id,payment_method,external_reference) where external_reference<>'' and reversal_of_id is null;

create or replace function public.salon_checkout_order(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_order_id bigint,p_request_key text,p_payments jsonb)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare v_order public.salon_orders;v_request public.salon_operation_requests;v_payment jsonb;v_account public.salon_member_accounts;v_payment_id bigint;v_method text;v_amount numeric(12,2);v_tendered numeric(12,2);v_change numeric(12,2);v_units numeric(12,3);v_account_id bigint;v_reference text;v_paid numeric(12,2);v_total_tendered numeric(12,2):=0;v_total_change numeric(12,2):=0;v_stock record;v_balance public.salon_inventory_balances;v_stock_ledger_id bigint;v_response jsonb;
begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','checkout');
 v_request:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'checkout','checkout_payload',hashtextextended(jsonb_build_object('order',p_order_id,'payments',p_payments)::text,0));if v_request.completed_at is not null then return v_request.response_json;end if;
 select * into v_order from public.salon_orders o where o.organization_id=p_organization_id and o.store_id=p_store_id and o.id=p_order_id for update;if not found then raise exception '订单不存在或不属于当前门店';end if;if v_order.status<>'awaiting_payment' then raise exception '只有待收银订单可以确认收款';end if;if jsonb_typeof(p_payments)<>'array' or jsonb_array_length(p_payments)=0 or jsonb_array_length(p_payments)>10 then raise exception '支付明细必须为1至10项';end if;
 select round(coalesce(sum((x->>'amount')::numeric),0),2) into v_paid from jsonb_array_elements(p_payments) x;if v_paid<>v_order.payable_total then raise exception '支付合计必须等于应收金额';end if;
 if exists(select 1 from jsonb_array_elements(p_payments) x where x->>'method' in ('member_value','member_units')) and not exists(select 1 from public.salon_customers c where c.organization_id=p_organization_id and c.id=v_order.customer_id and c.status='active') then raise exception '顾客当前不可使用会员账户';end if;
 perform 1 from public.salon_member_accounts a where a.organization_id=p_organization_id and a.id in(select distinct nullif(x->>'accountId','')::bigint from jsonb_array_elements(p_payments) x) order by a.id for update;
 for v_payment in select value from jsonb_array_elements(p_payments) loop
  v_method:=v_payment->>'method';v_amount:=round(coalesce(nullif(v_payment->>'amount','')::numeric,0),2);v_tendered:=round(coalesce(nullif(v_payment->>'tenderedAmount','')::numeric,v_amount),2);v_units:=round(coalesce(nullif(v_payment->>'units','')::numeric,0),3);v_account_id:=nullif(v_payment->>'accountId','')::bigint;v_reference:=btrim(coalesce(v_payment->>'externalReference',''));
  if v_method not in ('cash','wechat','alipay','member_value','member_units') or v_amount<=0 then raise exception '支付方式或金额无效';end if;
  if v_method='cash' then if v_tendered<v_amount then raise exception '现金实收不能低于本次支付金额';end if;v_change:=v_tendered-v_amount;elsif v_tendered<>v_amount then raise exception '非现金支付实收必须等于支付金额';else v_change:=0;end if;
  if v_method in ('wechat','alipay') and v_reference='' then raise exception '电子支付必须填写交易凭证号';end if;if v_method in ('cash','member_value','member_units') and v_reference<>'' then raise exception '当前支付方式不应填写电子凭证号';end if;
  if v_method in ('member_value','member_units') then select * into v_account from public.salon_member_accounts a where a.organization_id=p_organization_id and a.id=v_account_id and a.customer_id=v_order.customer_id and a.status='active' and (a.home_store_id=p_store_id or a.usable_scope='organization');if not found or (v_account.expires_on is not null and v_account.expires_on<current_date) then raise exception '会员账户不可核销';end if;if v_method='member_value' and (v_account.account_type<>'stored_value' or v_account.cash_balance<v_amount) then raise exception '储值余额不足或卡类型错误';end if;if v_method='member_units' and (v_account.account_type not in ('times_card','package') or v_units<=0 or v_account.remaining_units<v_units) then raise exception '次卡余次不足或卡类型错误';end if;end if;
  begin insert into public.salon_payments(organization_id,store_id,order_id,payment_method,amount,tendered_amount,change_amount,external_reference,member_account_id,member_units,status,confirmed_at) values(p_organization_id,p_store_id,p_order_id,v_method,v_amount,v_tendered,v_change,v_reference,v_account_id,v_units,'confirmed',now()) returning id into v_payment_id;exception when unique_violation then raise exception '电子支付凭证号已经使用';end;
  if v_method='member_value' then update public.salon_member_accounts set cash_balance=cash_balance-v_amount where organization_id=p_organization_id and id=v_account.id;insert into public.salon_account_ledger(organization_id,store_id,account_id,order_id,payment_id,entry_type,cash_delta,reason) values(p_organization_id,p_store_id,v_account.id,p_order_id,v_payment_id,'consume',-v_amount,'订单收银');elsif v_method='member_units' then update public.salon_member_accounts set remaining_units=remaining_units-v_units where organization_id=p_organization_id and id=v_account.id;insert into public.salon_account_ledger(organization_id,store_id,account_id,order_id,payment_id,entry_type,units_delta,reason) values(p_organization_id,p_store_id,v_account.id,p_order_id,v_payment_id,'consume',-v_units,'订单核销');end if;
  v_total_tendered:=v_total_tendered+v_tendered;v_total_change:=v_total_change+v_change;
 end loop;
 for v_stock in select l.catalog_item_id,sum(l.quantity)::numeric(14,3) quantity from public.salon_order_lines l where l.organization_id=p_organization_id and l.order_id=p_order_id and l.item_type='product' group by l.catalog_item_id order by l.catalog_item_id loop
  if not exists(select 1 from public.salon_catalog_store_settings s where s.organization_id=p_organization_id and s.store_id=p_store_id and s.catalog_item_id=v_stock.catalog_item_id and s.status='active' and s.stock_tracked) then raise exception '订单商品未启用当前门店库存';end if;select * into v_balance from public.salon_inventory_balances b where b.organization_id=p_organization_id and b.store_id=p_store_id and b.catalog_item_id=v_stock.catalog_item_id for update;if not found or v_balance.quantity<v_stock.quantity then raise exception '商品库存不足，收银已回滚';end if;
  update public.salon_inventory_balances set quantity=quantity-v_stock.quantity,updated_at=now() where organization_id=p_organization_id and store_id=p_store_id and catalog_item_id=v_stock.catalog_item_id;insert into public.salon_inventory_ledger(organization_id,store_id,catalog_item_id,movement_type,quantity_delta,quantity_before,quantity_after,order_id,reason) values(p_organization_id,p_store_id,v_stock.catalog_item_id,'sale',-v_stock.quantity,v_balance.quantity,v_balance.quantity-v_stock.quantity,p_order_id,'订单收银自动出库') returning id into v_stock_ledger_id;
 end loop;
 update public.salon_orders set status='paid',paid_at=now(),updated_at=now() where organization_id=p_organization_id and id=p_order_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'order',p_order_id::text,'checkout',jsonb_build_object('total',v_paid,'tendered',v_total_tendered,'change',v_total_change,'requestKey',p_request_key),'订单收银');v_response:=jsonb_build_object('orderId',p_order_id,'status','paid','paid',v_paid,'tendered',v_total_tendered,'change',v_total_change);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_request.id;return v_response;
end $$;

revoke execute on function public.salon_checkout_order(bigint,bigint,bigint,bigint,text,jsonb) from public,anon,authenticated;grant execute on function public.salon_checkout_order(bigint,bigint,bigint,bigint,text,jsonb) to service_role;
