-- D1: selected employee workflow retries and all customer portal read entry points.
set statement_timeout='30s';
set lock_timeout='5s';
alter table public.salon_operation_requests
 add column staff_request_actor_id bigint,
 add column staff_payload_digest bytea;

create function salon_private.claim_staff_request(
 p_organization_id bigint,p_store_id bigint,p_request_key text,p_action text,p_entity_type text,p_entity_id bigint,
 p_actor_staff_id bigint,p_payload jsonb,p_resource text,p_permission text
) returns public.salon_operation_requests language plpgsql security invoker set search_path='' as $$
declare v_op public.salon_operation_requests;v_digest bytea;
begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,p_resource,p_permission);
 if p_payload is null or jsonb_typeof(p_payload)<>'object' then raise exception '请求参数无效';end if;
 v_digest:=sha256(convert_to(p_payload::text,'UTF8'));
 v_op:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,p_action,p_entity_type,p_entity_id);
 select * into v_op from public.salon_operation_requests where id=v_op.id for update;
 if v_op.staff_request_actor_id is not null then
  if v_op.staff_request_actor_id<>p_actor_staff_id or v_op.staff_payload_digest is distinct from v_digest
   then raise exception '幂等键已被其他业务使用';end if;
 elsif v_op.completed_at is not null then
  raise exception '旧请求缺少身份校验信息，请核对业务记录';
 else
  update public.salon_operation_requests set staff_request_actor_id=p_actor_staff_id,staff_payload_digest=v_digest
   where id=v_op.id returning * into v_op;
 end if;
 return v_op;
end$$;
revoke execute on function salon_private.claim_staff_request(bigint,bigint,text,text,text,bigint,bigint,jsonb,text,text) from public,anon,authenticated;
grant execute on function salon_private.claim_staff_request(bigint,bigint,text,text,text,bigint,bigint,jsonb,text,text) to service_role;

create function salon_private.assert_customer_read_scope(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint)
returns bigint language plpgsql security invoker set search_path='' as $$
declare v_customer bigint;
begin
 select i.customer_id into v_customer from public.salon_customer_auth_identities i
 join public.salon_customers c on c.organization_id=i.organization_id and c.id=i.customer_id
 join public.salon_organizations o on o.id=i.organization_id
 join public.salon_stores s on s.organization_id=o.id and s.id=p_store_id
 where i.organization_id=p_organization_id and i.auth_user_id=p_auth_user_id
 and i.status='active' and c.status='active' and o.status='active' and s.status='active'
 for share of i,c,o,s;
 if not found then raise exception '顾客端账号未绑定或已停用，或门店不可用';end if;
 return v_customer;
end$$;
revoke execute on function salon_private.assert_customer_read_scope(uuid,bigint,bigint) from public,anon,authenticated;
grant execute on function salon_private.assert_customer_read_scope(uuid,bigint,bigint) to service_role;


create or replace function public.salon_bind_customer_identity(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_customer_id bigint,p_auth_user_id uuid,p_request_key text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'customers','write');
 if p_auth_user_id is null or nullif(btrim(coalesce(p_reason,'')),'') is null or not exists(select 1 from public.salon_customer_store_relations where organization_id=p_organization_id and store_id=p_store_id and customer_id=p_customer_id) then raise exception '顾客端绑定参数无效';end if;
 v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'customer_bind','customer_bind_payload',hashtextextended(jsonb_build_object('customer',p_customer_id,'authUser',p_auth_user_id)::text,0),p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_customer_id',p_customer_id,'p_auth_user_id',p_auth_user_id,'p_reason',p_reason),'customers','write');if v_op.completed_at is not null then return v_op.response_json;end if;
 begin insert into public.salon_customer_auth_identities(organization_id,customer_id,auth_user_id) values(p_organization_id,p_customer_id,p_auth_user_id) returning id into v_id;exception when unique_violation then raise exception '顾客或登录账号已经绑定';end;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'customer_identity',v_id::text,'bind',jsonb_build_object('customerId',p_customer_id),btrim(p_reason));
 v_response:=jsonb_build_object('identityId',v_id,'customerId',p_customer_id,'status','active');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_create_work(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_request_key text,p_customer_id bigint,p_order_id bigint,p_consent_id bigint,p_title text,p_description text,p_asset_ref text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','write');
 if nullif(btrim(coalesce(p_title,'')),'') is null or nullif(btrim(coalesce(p_asset_ref,'')),'') is null or not exists(select 1 from public.salon_staff where organization_id=p_organization_id and id=p_actor_staff_id and employment_status='active') or (p_customer_id is not null and not exists(select 1 from public.salon_customer_store_relations where organization_id=p_organization_id and store_id=p_store_id and customer_id=p_customer_id)) or (p_order_id is not null and not exists(select 1 from public.salon_orders where organization_id=p_organization_id and store_id=p_store_id and id=p_order_id and (p_customer_id is null or customer_id=p_customer_id))) then raise exception '作品参数无效';end if;
 if p_consent_id is not null and not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.store_id=p_store_id and c.id=p_consent_id and c.customer_id=p_customer_id and c.consent_type='work_publication' and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type=c.consent_type and r.status='revoked' and r.id>c.id)) then raise exception '作品公开授权无效或已撤回';end if;
 v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'work_create','work_payload',hashtextextended(jsonb_build_object('staff',p_actor_staff_id,'customer',p_customer_id,'order',p_order_id,'title',btrim(p_title),'asset',btrim(p_asset_ref))::text,0),p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_customer_id',p_customer_id,'p_order_id',p_order_id,'p_consent_id',p_consent_id,'p_title',p_title,'p_description',p_description,'p_asset_ref',p_asset_ref),'works','write');if v_op.completed_at is not null then return v_op.response_json;end if;
 insert into public.salon_works(organization_id,store_id,staff_id,customer_id,order_id,consent_id,title,description,asset_ref) values(p_organization_id,p_store_id,p_actor_staff_id,p_customer_id,p_order_id,p_consent_id,btrim(p_title),coalesce(p_description,''),btrim(p_asset_ref)) returning id into v_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'work',v_id::text,'create',jsonb_build_object('title',btrim(p_title),'customerId',p_customer_id,'orderId',p_order_id),'创建作品草稿');
 v_response:=jsonb_build_object('workId',v_id,'status','draft');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_submit_work(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_work_id bigint,p_request_key text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v public.salon_works;v_op public.salon_operation_requests;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','write');v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'work_submit','work',p_work_id,p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_work_id',p_work_id),'works','write');if v_op.completed_at is not null then return v_op.response_json;end if;
 select * into v from public.salon_works where organization_id=p_organization_id and store_id=p_store_id and id=p_work_id for update;if not found or v.staff_id<>p_actor_staff_id or v.status<>'draft' then raise exception '作品不存在、非本人作品或状态不能提交';end if;
 if v.customer_id is not null and (v.consent_id is null or not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.id=v.consent_id and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type='work_publication' and r.status='revoked' and r.id>c.id))) then raise exception '未取得有效顾客公开授权';end if;
 update public.salon_works set status='pending_review',submitted_at=now(),updated_at=now() where organization_id=p_organization_id and id=p_work_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'work',p_work_id::text,'submit',jsonb_build_object('status','pending_review'),'提交作品审核');v_response:=jsonb_build_object('workId',p_work_id,'status','pending_review');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_review_work(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_work_id bigint,p_request_key text,p_decision text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v public.salon_works;v_op public.salon_operation_requests;v_status text;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'works','review');if p_decision not in('published','rejected') or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '作品审核决定或说明无效';end if;
 v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'work_review','work',p_work_id,p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_work_id',p_work_id,'p_decision',p_decision,'p_reason',p_reason),'works','review');if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_works where organization_id=p_organization_id and store_id=p_store_id and id=p_work_id for update;if not found or v.status<>'pending_review' then raise exception '作品不存在或不在待审核状态';end if;if p_decision='published' and v.customer_id is not null and (v.consent_id is null or not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.id=v.consent_id and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type='work_publication' and r.status='revoked' and r.id>c.id))) then raise exception '顾客公开授权无效或已撤回';end if;
 v_status:=p_decision;update public.salon_works set status=v_status,reviewed_by_staff_id=p_actor_staff_id,reviewed_at=now(),review_reason=btrim(p_reason),published_at=case when v_status='published' then now() end,updated_at=now() where organization_id=p_organization_id and id=p_work_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'work',p_work_id::text,'review',jsonb_build_object('status',v.status),jsonb_build_object('status',v_status),btrim(p_reason));v_response:=jsonb_build_object('workId',p_work_id,'status',v_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_moderate_review(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_review_id bigint,p_request_key text,p_status text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v public.salon_reviews;v_op public.salon_operation_requests;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'reviews','moderate');if p_status not in('published','hidden') or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '评价处理状态或原因无效';end if;v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'review_moderate','review',p_review_id,p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_review_id',p_review_id,'p_status',p_status,'p_reason',p_reason),'reviews','moderate');if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_reviews where organization_id=p_organization_id and store_id=p_store_id and id=p_review_id for update;if not found or v.status=p_status then raise exception '评价不存在或已经是目标状态';end if;update public.salon_reviews set status=p_status,moderated_by_staff_id=p_actor_staff_id,moderated_at=now(),moderation_reason=btrim(p_reason) where organization_id=p_organization_id and id=p_review_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'review',p_review_id::text,'moderate',jsonb_build_object('status',v.status),jsonb_build_object('status',p_status),btrim(p_reason));v_response:=jsonb_build_object('reviewId',p_review_id,'status',p_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_create_campaign(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_request_key text,p_name text,p_channel text,p_audience_json jsonb,p_message_template text,p_starts_on date,p_ends_on date)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v_op public.salon_operation_requests;v_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'marketing','write');if nullif(btrim(coalesce(p_name,'')),'') is null or p_channel not in('in_app','wechat_manual','sms_manual') or jsonb_typeof(coalesce(p_audience_json,'{}'))<>'object' or p_starts_on is null or p_ends_on<p_starts_on then raise exception '营销活动参数无效';end if;v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'campaign_create','campaign_payload',hashtextextended(jsonb_build_object('name',btrim(p_name),'channel',p_channel,'starts',p_starts_on,'ends',p_ends_on)::text,0),p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_name',p_name,'p_channel',p_channel,'p_audience_json',p_audience_json,'p_message_template',p_message_template,'p_starts_on',p_starts_on,'p_ends_on',p_ends_on),'marketing','write');if v_op.completed_at is not null then return v_op.response_json;end if;insert into public.salon_campaigns(organization_id,store_id,name,channel,audience_json,message_template,starts_on,ends_on,created_by_staff_id,updated_by_staff_id) values(p_organization_id,p_store_id,btrim(p_name),p_channel,p_audience_json,coalesce(p_message_template,''),p_starts_on,p_ends_on,p_actor_staff_id,p_actor_staff_id) returning id into v_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'campaign',v_id::text,'create',jsonb_build_object('name',btrim(p_name),'channel',p_channel,'startsOn',p_starts_on,'endsOn',p_ends_on),'创建营销活动草稿');v_response:=jsonb_build_object('campaignId',v_id,'status','draft');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_set_campaign_status(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_campaign_id bigint,p_request_key text,p_status text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v public.salon_campaigns;v_op public.salon_operation_requests;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'marketing','write');if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '活动状态变更原因不能为空';end if;v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'campaign_status','campaign',p_campaign_id,p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_campaign_id',p_campaign_id,'p_status',p_status,'p_reason',p_reason),'marketing','write');if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_campaigns where organization_id=p_organization_id and store_id=p_store_id and id=p_campaign_id for update;if not found or not((v.status='draft' and p_status in('active','cancelled'))or(v.status='active' and p_status in('paused','ended','cancelled'))or(v.status='paused' and p_status in('active','ended','cancelled'))) then raise exception '活动不存在或状态变更无效';end if;if p_status='active' and not exists(select 1 from public.salon_customer_consents c where c.organization_id=p_organization_id and c.store_id=p_store_id and c.consent_type='marketing_messages' and c.status='granted' and not exists(select 1 from public.salon_customer_consents r where r.organization_id=c.organization_id and r.store_id=c.store_id and r.customer_id=c.customer_id and r.consent_type=c.consent_type and r.status='revoked' and r.id>c.id)) then raise exception '当前门店没有有效营销授权顾客，不能启用活动';end if;update public.salon_campaigns set status=p_status,updated_by_staff_id=p_actor_staff_id,updated_at=now() where organization_id=p_organization_id and id=p_campaign_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'campaign',p_campaign_id::text,'status',jsonb_build_object('status',v.status),jsonb_build_object('status',p_status),btrim(p_reason));v_response:=jsonb_build_object('campaignId',p_campaign_id,'status',p_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_review_customer_booking(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_booking_request_id bigint,p_request_key text,p_decision text,p_staff_id bigint,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' set timezone='UTC' as $$declare v public.salon_customer_booking_requests;v_op public.salon_operation_requests;v_result jsonb;v_appointment_id bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'customer_portal','manage');if p_decision not in('confirmed','rejected') or nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception '预约处理决定或原因无效';end if;v_op:=salon_private.claim_staff_request(p_organization_id,p_store_id,p_request_key,'booking_review','booking_request',p_booking_request_id,p_actor_staff_id,jsonb_build_object('p_actor_staff_id',p_actor_staff_id,'p_organization_id',p_organization_id,'p_store_id',p_store_id,'p_booking_request_id',p_booking_request_id,'p_decision',p_decision,'p_staff_id',p_staff_id,'p_reason',p_reason),'customer_portal','manage');if v_op.completed_at is not null then return v_op.response_json;end if;select * into v from public.salon_customer_booking_requests where organization_id=p_organization_id and store_id=p_store_id and id=p_booking_request_id for update;if not found or v.status<>'submitted' then raise exception '预约申请不存在或已经处理';end if;if p_decision='confirmed' then v_result:=public.salon_create_appointment(p_actor_staff_id,p_organization_id,p_store_id,coalesce(p_staff_id,v.staff_id),v.customer_id,v.starts_at,v.ends_at,'customer_portal',v.notes);v_appointment_id:=(v_result->>'appointmentId')::bigint;end if;update public.salon_customer_booking_requests set status=p_decision,appointment_id=v_appointment_id,staff_id=coalesce(p_staff_id,staff_id),handled_by_staff_id=p_actor_staff_id,handled_at=now(),handle_reason=btrim(p_reason),updated_at=now() where organization_id=p_organization_id and id=p_booking_request_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'customer_booking',p_booking_request_id::text,'review',jsonb_build_object('status',v.status),jsonb_build_object('status',p_decision,'appointmentId',v_appointment_id),btrim(p_reason));v_response:=jsonb_build_object('bookingRequestId',p_booking_request_id,'status',p_decision,'appointmentId',v_appointment_id);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_op.id;return v_response;end$$;


create or replace function public.salon_customer_list_public_works(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_limit integer default 100) returns table(id bigint,title text,description text,asset_ref text,staff_id bigint,published_at timestamptz) language plpgsql security invoker set search_path='' as $$begin perform salon_private.assert_customer_read_scope(p_auth_user_id,p_organization_id,p_store_id); if not exists(select 1 from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active') or p_limit not between 1 and 200 then raise exception '顾客端身份或查询数量无效';end if;return query select w.id,w.title,w.description,w.asset_ref,w.staff_id,w.published_at from public.salon_works w where w.organization_id=p_organization_id and w.store_id=p_store_id and w.status='published' order by w.published_at desc,w.id desc limit p_limit;end$$;


create or replace function public.salon_customer_list_bookings(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint,p_limit integer default 100) returns setof public.salon_customer_booking_requests language plpgsql security invoker set search_path='' as $$declare v_customer bigint;begin perform salon_private.assert_customer_read_scope(p_auth_user_id,p_organization_id,p_store_id); select customer_id into v_customer from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active';if not found or p_limit not between 1 and 200 then raise exception '顾客端身份或查询数量无效';end if;return query select * from public.salon_customer_booking_requests where organization_id=p_organization_id and store_id=p_store_id and customer_id=v_customer order by created_at desc,id desc limit p_limit;end$$;


create or replace function public.salon_customer_list_booking_options(p_auth_user_id uuid,p_organization_id bigint,p_store_id bigint) returns jsonb language plpgsql security invoker set search_path='' as $$declare v_result jsonb;begin perform salon_private.assert_customer_read_scope(p_auth_user_id,p_organization_id,p_store_id); if not exists(select 1 from public.salon_customer_auth_identities where organization_id=p_organization_id and auth_user_id=p_auth_user_id and status='active') or not exists(select 1 from public.salon_stores where organization_id=p_organization_id and id=p_store_id and status='active') then raise exception '顾客端身份或门店无效';end if;select jsonb_build_object('services',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'code',i.code,'name',i.name,'category',i.category,'price',case when i.member_price>0 then i.member_price else i.list_price end,'durationMinutes',i.duration_minutes) order by i.category,i.name) from public.salon_catalog_items i join public.salon_catalog_store_settings s on s.organization_id=i.organization_id and s.catalog_item_id=i.id and s.store_id=p_store_id and s.status='active' where i.organization_id=p_organization_id and i.item_type='service' and i.status='active'),'[]'::jsonb),'staff',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'displayName',x.display_name,'position',x.position,'levelName',x.level_name) order by x.display_name) from public.salon_staff x where x.organization_id=p_organization_id and x.store_id=p_store_id and x.employment_status='active'),'[]'::jsonb)) into v_result;return v_result;end$$;


create or replace function public.salon_customer_get_context(p_auth_user_id uuid) returns jsonb language plpgsql security invoker set search_path='' as $$declare v_result jsonb;begin select jsonb_agg(jsonb_build_object('organizationId',i.organization_id,'customerId',i.customer_id,'displayName',c.display_name,'stores',coalesce((select jsonb_agg(jsonb_build_object('storeId',s.id,'code',s.code,'name',s.name) order by s.id) from public.salon_stores s where s.organization_id=i.organization_id and s.status='active'),'[]'::jsonb)) order by i.organization_id) into v_result from public.salon_customer_auth_identities i join public.salon_customers c on c.organization_id=i.organization_id and c.id=i.customer_id and c.status='active' join public.salon_organizations o on o.id=i.organization_id and o.status='active' where i.auth_user_id=p_auth_user_id and i.status='active';if v_result is null then raise exception '顾客端账号未绑定或已停用';end if;return v_result;end$$;
