-- Atomic order drafting, line replacement and lifecycle. Development only.
set statement_timeout='30s';set lock_timeout='5s';
create sequence public.salon_order_number_seq;revoke all on sequence public.salon_order_number_seq from public,anon,authenticated;grant usage,select on sequence public.salon_order_number_seq to service_role;
alter table public.salon_orders add column created_by_staff_id bigint,add column notes text not null default '',add column discount_reason text not null default '',add column updated_at timestamptz not null default now(),add foreign key(organization_id,created_by_staff_id) references public.salon_staff(organization_id,id) on delete restrict;
alter table public.salon_order_lines add column item_code text not null default '',add column item_name text not null default '',add column item_type text not null default '',add column discount_amount numeric(12,2) not null default 0 check(discount_amount>=0),add column created_at timestamptz not null default now();
alter table public.salon_operation_requests drop constraint salon_operation_requests_action_check;alter table public.salon_operation_requests add constraint salon_operation_requests_action_check check(action in ('checkout','refund','inventory_move','customer_create','customer_status','customer_relation','catalog_create','catalog_enable','catalog_status','inventory_count','member_open','member_recharge','member_status','order_create','order_lines','order_status'));

create or replace function public.salon_create_order(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_request_key text,p_customer_id bigint default null,p_appointment_id bigint default null,p_notes text default '')
returns jsonb language plpgsql security invoker set search_path='' as $$ declare v_request public.salon_operation_requests;v_id bigint;v_no text;v_hash bigint;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','write');
 if p_customer_id is not null and not exists(select 1 from public.salon_customers c join public.salon_customer_store_relations r on r.organization_id=c.organization_id and r.customer_id=c.id where c.organization_id=p_organization_id and c.id=p_customer_id and c.status='active' and r.store_id=p_store_id) then raise exception '顾客不存在、已冻结或不属于当前门店';end if;
 if p_appointment_id is not null and not exists(select 1 from public.salon_appointments a where a.organization_id=p_organization_id and a.store_id=p_store_id and a.id=p_appointment_id and (p_customer_id is null or a.customer_id=p_customer_id)) then raise exception '预约不存在、跨店或顾客不一致';end if;
 v_hash:=hashtextextended(jsonb_build_object('customer',p_customer_id,'appointment',p_appointment_id,'notes',btrim(coalesce(p_notes,'')))::text,0);v_request:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'order_create','order_payload',v_hash);if v_request.completed_at is not null then return v_request.response_json;end if;
 v_no:='S'||p_store_id::text||'-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(nextval('public.salon_order_number_seq')::text,8,'0');insert into public.salon_orders(organization_id,store_id,order_no,customer_id,appointment_id,status,created_by_staff_id,notes) values(p_organization_id,p_store_id,v_no,p_customer_id,p_appointment_id,'draft',p_actor_staff_id,btrim(coalesce(p_notes,''))) returning id into v_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json) values(p_organization_id,p_store_id,p_actor_staff_id,'order',v_id::text,'create',jsonb_build_object('orderNo',v_no,'customerId',p_customer_id,'appointmentId',p_appointment_id));v_response:=jsonb_build_object('orderId',v_id,'orderNo',v_no,'status','draft');update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_request.id;return v_response;
end $$;

create or replace function public.salon_replace_order_lines(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_order_id bigint,p_request_key text,p_lines jsonb,p_discount_reason text default '')
returns jsonb language plpgsql security invoker set search_path='' as $$ declare v_request public.salon_operation_requests;v_order public.salon_orders;v_line jsonb;v_item public.salon_catalog_items;v_qty numeric;v_price numeric;v_discount numeric;v_staff bigint;v_subtotal numeric:=0;v_discount_total numeric:=0;v_payable numeric:=0;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','write');v_request:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'order_lines','order_lines_payload',hashtextextended(jsonb_build_object('order',p_order_id,'lines',p_lines,'reason',btrim(coalesce(p_discount_reason,'')))::text,0));if v_request.completed_at is not null then return v_request.response_json;end if;
 select * into v_order from public.salon_orders where organization_id=p_organization_id and store_id=p_store_id and id=p_order_id for update;if not found then raise exception '订单不存在或不属于当前门店';end if;if v_order.status<>'draft' then raise exception '只有草稿订单可以修改明细';end if;if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 or jsonb_array_length(p_lines)>100 then raise exception '订单明细必须为1至100项';end if;
 delete from public.salon_order_lines where organization_id=p_organization_id and order_id=p_order_id;
 for v_line in select value from jsonb_array_elements(p_lines) loop
  select i.* into v_item from public.salon_catalog_items i join public.salon_catalog_store_settings s on s.organization_id=i.organization_id and s.catalog_item_id=i.id where i.organization_id=p_organization_id and i.id=nullif(v_line->>'catalogItemId','')::bigint and i.status='active' and s.store_id=p_store_id and s.status='active';if not found then raise exception '订单项目商品不存在或当前门店未启用';end if;
  v_qty:=round(coalesce(nullif(v_line->>'quantity','')::numeric,0),3);v_price:=round(coalesce(nullif(v_line->>'unitPrice','')::numeric,v_item.list_price),2);v_discount:=round(coalesce(nullif(v_line->>'discountAmount','')::numeric,0),2);v_staff:=nullif(v_line->>'staffId','')::bigint;
  if v_qty<=0 or v_price<0 or v_discount<0 or v_discount>v_qty*v_price then raise exception '订单明细数量、单价或优惠无效';end if;if v_staff is not null and not exists(select 1 from public.salon_staff s where s.organization_id=p_organization_id and s.store_id=p_store_id and s.id=v_staff and s.employment_status='active') then raise exception '服务员工不是当前门店在职员工';end if;
  v_subtotal:=v_subtotal+v_qty*v_price;v_discount_total:=v_discount_total+v_discount;v_payable:=v_payable+v_qty*v_price-v_discount;
  insert into public.salon_order_lines(organization_id,order_id,catalog_item_id,staff_id,quantity,unit_price,line_total,item_code,item_name,item_type,discount_amount) values(p_organization_id,p_order_id,v_item.id,v_staff,v_qty,v_price,round(v_qty*v_price-v_discount,2),v_item.code,v_item.name,v_item.item_type,v_discount);
 end loop;
 if v_discount_total>0 then perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','discount');if nullif(btrim(p_discount_reason),'') is null then raise exception '优惠订单必须填写原因';end if;end if;
 update public.salon_orders set subtotal=round(v_subtotal,2),discount_total=round(v_discount_total,2),payable_total=round(v_payable,2),discount_reason=btrim(coalesce(p_discount_reason,'')),updated_at=now() where organization_id=p_organization_id and id=p_order_id;
 insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'order',p_order_id::text,'replace_lines',jsonb_build_object('lineCount',jsonb_array_length(p_lines),'subtotal',round(v_subtotal,2),'discount',round(v_discount_total,2),'payable',round(v_payable,2),'requestKey',p_request_key),btrim(coalesce(p_discount_reason,'')));
 v_response:=jsonb_build_object('orderId',p_order_id,'lineCount',jsonb_array_length(p_lines),'subtotal',round(v_subtotal,2),'discountTotal',round(v_discount_total,2),'payableTotal',round(v_payable,2));update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_request.id;return v_response;
end $$;

create or replace function public.salon_set_order_status(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_order_id bigint,p_request_key text,p_status text,p_reason text default '')
returns jsonb language plpgsql security invoker set search_path='' as $$ declare v_request public.salon_operation_requests;v_order public.salon_orders;v_response jsonb;begin
 perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','write');v_request:=salon_private.claim_request(p_organization_id,p_store_id,p_request_key,'order_status','order_status_'||coalesce(p_status,''),p_order_id);if v_request.completed_at is not null then return v_request.response_json;end if;select * into v_order from public.salon_orders where organization_id=p_organization_id and store_id=p_store_id and id=p_order_id for update;if not found then raise exception '订单不存在或不属于当前门店';end if;
 if not ((v_order.status='draft' and p_status in ('opened','cancelled')) or (v_order.status='opened' and p_status in ('in_service','awaiting_payment','cancelled')) or (v_order.status='in_service' and p_status in ('awaiting_payment','cancelled'))) then raise exception '订单状态流转无效';end if;if p_status<>'cancelled' and not exists(select 1 from public.salon_order_lines where organization_id=p_organization_id and order_id=p_order_id) then raise exception '空订单不能进入业务流程';end if;if p_status='cancelled' and nullif(btrim(p_reason),'') is null then raise exception '取消订单必须填写原因';end if;
 update public.salon_orders set status=p_status,opened_at=case when p_status='opened' then now() else opened_at end,updated_at=now() where organization_id=p_organization_id and id=p_order_id;insert into public.salon_audit_events(organization_id,store_id,actor_staff_id,entity_type,entity_id,action,before_json,after_json,reason) values(p_organization_id,p_store_id,p_actor_staff_id,'order',p_order_id::text,'status_change',jsonb_build_object('status',v_order.status),jsonb_build_object('status',p_status),btrim(coalesce(p_reason,'')));v_response:=jsonb_build_object('orderId',p_order_id,'status',p_status);update public.salon_operation_requests set response_json=v_response,completed_at=now() where id=v_request.id;return v_response;
end $$;

create or replace function public.salon_get_order(p_actor_staff_id bigint,p_organization_id bigint,p_store_id bigint,p_order_id bigint)
returns jsonb language plpgsql security invoker set search_path='' as $$ declare v_order jsonb;v_lines jsonb;begin perform salon_private.assert_staff_permission(p_actor_staff_id,p_organization_id,p_store_id,'orders','read');select to_jsonb(o) into v_order from public.salon_orders o where o.organization_id=p_organization_id and o.store_id=p_store_id and o.id=p_order_id;if v_order is null then raise exception '订单不存在或不属于当前门店';end if;select coalesce(jsonb_agg(to_jsonb(l) order by l.id),'[]'::jsonb) into v_lines from public.salon_order_lines l where l.organization_id=p_organization_id and l.order_id=p_order_id;return jsonb_build_object('order',v_order,'lines',v_lines);end $$;

revoke execute on function public.salon_create_order(bigint,bigint,bigint,text,bigint,bigint,text) from public,anon,authenticated;revoke execute on function public.salon_replace_order_lines(bigint,bigint,bigint,bigint,text,jsonb,text) from public,anon,authenticated;revoke execute on function public.salon_set_order_status(bigint,bigint,bigint,bigint,text,text,text) from public,anon,authenticated;revoke execute on function public.salon_get_order(bigint,bigint,bigint,bigint) from public,anon,authenticated;
grant execute on function public.salon_create_order(bigint,bigint,bigint,text,bigint,bigint,text) to service_role;grant execute on function public.salon_replace_order_lines(bigint,bigint,bigint,bigint,text,jsonb,text) to service_role;grant execute on function public.salon_set_order_status(bigint,bigint,bigint,bigint,text,text,text) to service_role;grant execute on function public.salon_get_order(bigint,bigint,bigint,bigint) to service_role;
